/**
 * Server-side copy of the 11 modules' quiz answer keys (per contracts.md §4
 * M11: "the owning agent duplicates a minimal server-side copy of answer
 * keys under apps/api/src/services/checklist/, kept in sync with the content
 * module by convention/tests"). Source of truth for the actual question
 * text/options remains apps/web/src/content/modules/*.ts (content-writer);
 * this file only needs id -> correctIndex + explanation to score a submission
 * without a cross-app import. Mechanically generated from that content once;
 * if content-writer changes a quiz's correct answer, this file must be
 * updated to match (checklist.test.ts asserts every quizId/questionId this
 * route might see resolves to an entry here).
 */

export interface QuizAnswerKeyEntry {
  correctIndex: number;
  explanation: string;
}

export const QUIZ_ANSWER_KEYS: Record<string, Record<string, QuizAnswerKeyEntry>> = {
  advanced: {
    "advanced-q1": { correctIndex: 1, explanation: "Real attention weights aren't exposed by hosted provider APIs, so any 'attention visualization' against a real model has to be an approximation. This app is explicit about that limitation rather than presenting a heuristic as if it were ground truth — a distinction that matters for any claim built on top of it." },
    "advanced-q2": { correctIndex: 1, explanation: "Quantization's quality impact is architecture- and task-dependent — a retention figure from one model/task combination doesn't transfer reliably to a different one, especially for precision-sensitive tasks. The correct response is to measure it on your actual deployment target, not to treat any single number as universal." },
    "advanced-q3": { correctIndex: 1, explanation: "The architecture deliberately avoids duplicating generation code: thinking budget is one more tunable parameter on the same generation pipeline M1 already built, so reusing `/fundamentals/sample` with `params.thinkingBudget` set from the preset is the correct design, not a shortcut." },
    "advanced-q4": { correctIndex: 1, explanation: "RAG is specifically suited to knowledge that changes frequently or is private, because it injects current information per-request without any retraining. Fine-tuning/LoRA are better matched to ingraining a stable behavior, style, or format — re-fine-tuning weekly to chase changing facts is a mismatch between the technique and the actual constraint." },
    "advanced-q5": { correctIndex: 1, explanation: "Extended deliberation helps multi-step tasks up to a point, but past that point it can plateau or even introduce new failure modes (e.g. overanalyzing a simple problem into a wrong answer), while cost and latency keep climbing regardless. Budgets need empirical, per-task tuning rather than a 'more is always better' default." },
  },
  agents: {
    "agents-q1": { correctIndex: 1, explanation: "Prompt instructions are a soft, probabilistic nudge at best. The tool registry/allow-list is a structural control — if a tool isn't in the list passed for that run, the agent literally has no way to call it, regardless of what the model generates." },
    "agents-q2": { correctIndex: 1, explanation: "Loop detection specifically monitors for near-identical repetition within a window — it catches pathological non-progress earlier and cheaper than letting the run exhaust its full step budget. max_steps is a hard ceiling that fires regardless of whether progress looked healthy or not." },
    "agents-q3": { correctIndex: 1, explanation: "A timed-out approval fails safely and explicitly: the stream emits an error step, a run_complete with stopReason 'timeout', and then the terminal done event — never a silent hang or an automatic self-approval." },
    "agents-q4": { correctIndex: 1, explanation: "HITL's protective value depends on approvals actually being scrutinized. If every request is approved near-instantly regardless of content, that's a signal the review step may have become a formality rather than a real safeguard — worth auditing, not celebrating." },
    "agents-q5": { correctIndex: 1, explanation: "Long-term memory retrieval has no built-in way to distinguish a verified fact from a previously-wrong conclusion unless the system explicitly tracks that metadata and provides a way to correct or decay entries. Without it, errors compound silently across runs." },
  },
  checklist: {
    "checklist-q1": { correctIndex: 1, explanation: "CLAUDE.md is explicit that Learn text, glossary, and quizzes are typed content owned by content-writer, not hardcoded in components or served dynamically — the glossary is static enough, and used widely enough (tooltips everywhere), that build-time content is the right fit." },
    "checklist-q2": { correctIndex: 1, explanation: "The checklist exists to track progress through real understanding, not to be gamed as a completion metric. An item checked off without being able to explain its underlying failure mode and fix hasn't actually achieved what the checklist is tracking." },
    "checklist-q3": { correctIndex: 1, explanation: "A bare score tells you whether you were right, not why. Explanations for every question (including correct ones) are what make a quiz a learning tool rather than just a test — this is consistent with how quizzes are designed across every module in this app." },
    "checklist-q4": { correctIndex: 1, explanation: "Cross-module related links (e.g. a security term relating to a prompting term) reflect real conceptual overlap — prompt injection, for instance, is both a prompting-template concern and a security concern. Following those links across modules is part of building the full picture." },
    "checklist-q5": { correctIndex: 1, explanation: "This is explicitly documented as a decision framework, not a computation — the right choice depends on project-specific constraints (data freshness, latency budget, team capacity) that no single API call could capture. It narrows the search space; the engineer still has to apply judgment." },
  },
  embeddings: {
    "embeddings-q1": { correctIndex: 1, explanation: "Cosine similarity measures orientation (the angle) between vectors, not their length — which is why it's the preferred metric for embedding models trained/normalized so that direction carries the semantic signal rather than magnitude." },
    "embeddings-q2": { correctIndex: 2, explanation: "Different embedding models (or versions) produce vectors in incompatible spaces. If dimensions happen to match, there's often no error at all — just silently wrong similarity scores, which is why a model change requires a full corpus re-embed, not an incremental update." },
    "embeddings-q3": { correctIndex: 1, explanation: "BM25 excels at exact lexical matches (codes, rare names) that embeddings can blur past; dense vector search excels at semantic paraphrases BM25 can't match. Their complementary strengths are exactly why fusing them outperforms either alone on real-world query mixes." },
    "embeddings-q4": { correctIndex: 1, explanation: "A BM25 score of 12.4 and a cosine similarity of 0.82 aren't comparable magnitudes. RRF sidesteps this entirely by using each result's rank position in its own list, which is why it's the standard way to fuse heterogeneous retrievers without one silently dominating." },
    "embeddings-q5": { correctIndex: 1, explanation: "Flat search is exhaustive and exact, which guarantees perfect recall but doesn't scale past tens of thousands of vectors at interactive latency. HNSW builds a graph structure to prune most of the search space, trading a tunable amount of recall for much better scalability, at higher memory cost than a simple flat array." },
  },
  evals: {
    "evals-q1": { correctIndex: 1, explanation: "A golden dataset's value comes entirely from consistency: running the identical cases against two variants produces comparable scores, which is what makes 'is this actually better' a measurable question instead of a subjective impression." },
    "evals-q2": { correctIndex: 1, explanation: "Position bias is well-documented across judge models — the preferred response can flip purely based on presentation order. Running both orders and checking for agreement is the standard way to detect and discard order-driven, non-quality-based verdicts." },
    "evals-q3": { correctIndex: 0, explanation: "Context precision and faithfulness measure different stages: precision is about whether retrieved chunks are relevant (retrieval-stage), faithfulness is about whether the generated answer sticks to what was retrieved (generation-stage). Low precision with high faithfulness points to a retrieval-tuning problem, not a generation problem." },
    "evals-q4": { correctIndex: 1, explanation: "Using a judge from the same family as one of the compared models introduces a systematic thumb on the scale favoring that model. A fair cross-provider comparison needs a judge model with no family relationship to any candidate being compared." },
    "evals-q5": { correctIndex: 1, explanation: "An eval suite result aggregates many individual calls. Persisting each one as its own Run (with judgeRunId linking judge calls to what they evaluated) means nothing about the final aggregate score is a black box — any specific case or judgment can be inspected directly." },
  },
  fundamentals: {
    "fundamentals-q1": { correctIndex: 1, explanation: "Sub-word tokenizers (like BPE) split uncommon words, code, and non-English text into multiple tokens because those sequences weren't common enough to earn their own single token in the vocabulary. Word count is not a reliable proxy for token count." },
    "fundamentals-q2": { correctIndex: 1, explanation: "Hosted multi-tenant providers describe seeded, zero-temperature generation as 'best-effort' deterministic — variance can still creep in from infrastructure-level factors outside the sampling algorithm itself. True guaranteed determinism requires a fully controlled stack (e.g. the MockProvider or a local model)." },
    "fundamentals-q3": { correctIndex: 1, explanation: "TTFT is dominated by the prefill phase, which processes the entire input (system prompt + context + history) in one pass before the first output token can be produced. A short requested output doesn't help TTFT at all — it only affects total decode time." },
    "fundamentals-q4": { correctIndex: 2, explanation: "top_p and top_k are independent truncations applied to the same distribution; the narrower one in practice determines the candidate set at each step. A top_p of 0.1 will almost always produce a smaller candidate set than top_k=500 for any typical distribution, making the top_k setting effectively a no-op here." },
    "fundamentals-q5": { correctIndex: 0, explanation: "The project's acceptance criteria explicitly require that changing temperature and seeing token-probability shifts work with zero keys configured. That means the MockProvider's determinism and parameter-sensitivity aren't incidental — they're the mechanism that makes the whole fundamentals module teach something real without any provider setup." },
  },
  production: {
    "production-q1": { correctIndex: 1, explanation: "The spec explicitly calls for 'measured savings' from actually running requests through the provider twice (cold vs. simulated-cache), specifically because assumed multipliers are a common way cost projections turn out to be wrong once deployed against real traffic." },
    "production-q2": { correctIndex: 1, explanation: "A timeout means you don't know whether the original request succeeded on the server side. Without an idempotency key letting the server recognize and deduplicate the retry, a non-idempotent action like a charge can be executed twice." },
    "production-q3": { correctIndex: 1, explanation: "Retries with backoff are designed for brief, isolated failures where trying again shortly after is likely to succeed. A circuit breaker is designed for sustained failures, protecting both the caller and the struggling dependency by stopping traffic entirely until a cooldown passes and trial requests confirm recovery." },
    "production-q4": { correctIndex: 1, explanation: "A queue with no depth cap keeps accepting work it can't actually process in time, which both delays the eventual failure and risks exhausting memory. A production-grade queue bounds its depth and fails fast (sheds load) once full." },
    "production-q5": { correctIndex: 1, explanation: "Shadowing and canarying answer different questions: shadowing is safe but blind to real user reaction; canarying exposes real (small) risk but captures genuine user-facing signal. A regression surfacing only in canary, not shadow, is exactly the gap shadow deployment cannot cover on its own." },
  },
  prompting: {
    "prompting-q1": { correctIndex: 1, explanation: "Few-shot examples cost tokens on every call (compounding at scale) and can anchor the model onto a narrower pattern than intended, especially if examples are poorly chosen or ordered. It's a real trade-off, not a free upgrade — zero-shot is the right default to try first." },
    "prompting-q2": { correctIndex: 1, explanation: "Indirect prompt injection specifically refers to malicious instructions arriving through content the application trusts as 'data to process' — a retrieved document, a tool result, a scraped page — rather than through the user's own input. It's generally considered higher-risk than direct injection because the user never typed the malicious text themselves." },
    "prompting-q3": { correctIndex: 1, explanation: "Multi-step prompting techniques are multiple real LLM calls. Linking each one via parentRunId lets the Run Inspector show the full causal chain — which sub-call cost what, took how long, and produced what intermediate output — instead of collapsing everything into a single misleading summary." },
    "prompting-q4": { correctIndex: 1, explanation: "Models trained to weight system/developer instructions above user and untrusted content do measurably resist injection better, but this is a trained tendency, not an enforced rule — a sufficiently crafted input can still sometimes succeed. Real enforcement (tool allow-lists, output validation, least privilege) has to happen in code." },
    "prompting-q5": { correctIndex: 1, explanation: "This app's prompt versioning is append-only by design (PUT creates a new version with a parentVersionId, never mutates history), which is essential for diffing and regression gating — but it means whatever feature/eval consumed the old version id has to be explicitly repointed to the new one." },
  },
  rag: {
    "rag-q1": { correctIndex: 1, explanation: "Faithfulness and factual correctness are deliberately separate concepts. A faithful answer accurately reflects what the retrieved context said — if that context was wrong or stale, a perfectly faithful answer can still be a wrong answer. This is a data-quality problem, not a generation problem." },
    "rag-q2": { correctIndex: 1, explanation: "Raising top-k improves recall (less likely to miss needed info) but can hurt precision (more irrelevant chunks mixed in) and increases the risk that a needed chunk lands in a context position the model pays less attention to. Reranking/compression down to a smaller precise set is usually a better fix than just raising top-k." },
    "rag-q3": { correctIndex: 1, explanation: "HyDE addresses the lexical/structural gap between terse queries and longer documents by embedding a hypothetical answer (closer in style to real documents) instead of the bare query. It helps most when that gap is large — short, under-specified, or differently-phrased queries." },
    "rag-q4": { correctIndex: 1, explanation: "RAG retrieves from whatever is actually stored in the vector index, not from some live view of the source document. If an update to the source doesn't trigger re-chunking, re-embedding, and re-indexing, the old vectors remain live and keep getting retrieved — this is the 'stale' failure mode this app's failure-mode-demo deliberately reproduces." },
    "rag-q5": { correctIndex: 1, explanation: "Agentic RAG turns retrieval into a tool the model can call repeatedly and adaptively, which is powerful but inherits every general agent risk — looping, excessive calls, unpredictable cost — so it needs explicit max-steps/budget/timeout limits, not a RAG-specific exemption from them." },
  },
  security: {
    "security-q1": { correctIndex: 1, explanation: "Indirect injection hides malicious instructions inside retrieved or tool-sourced content that the application implicitly trusts as 'data,' rather than coming from anything the user themselves typed — which is exactly why it's often considered higher-risk: the victim did nothing wrong." },
    "security-q2": { correctIndex: 1, explanation: "Instruction hierarchy measurably reduces injection success rates but is not an absolute guarantee — it's one layer in a defense-in-depth strategy, not a substitute for code-level enforcement like tool allow-lists and output validation." },
    "security-q3": { correctIndex: 1, explanation: "Defense in depth assumes any single layer can be bypassed — the question for a mature guardrail system is always 'what's the next independent layer that still catches this,' not whether any one layer can be made perfect." },
    "security-q4": { correctIndex: 1, explanation: "CLAUDE.md requires the vulnerable bot and its attacks to be contained to the app and safe to run even with real provider keys configured. Keeping payloads server-side (not shipped as reusable client-side strings) reduces the risk of them being copy-pasted and tried against an unrelated real system by accident." },
    "security-q5": { correctIndex: 1, explanation: "Tool abuse doesn't require a new exploit — it hijacks existing legitimate capability via injected instructions. The mitigation that actually works regardless of how the bad call was triggered is gating dangerous tools behind human review or strict validation, not trusting prompt-level instructions to prevent misuse." },
  },
  structured: {
    "structured-q1": { correctIndex: 1, explanation: "JSON mode constrains decoding to produce syntactically valid JSON by masking invalid tokens, but it has no awareness of your specific schema's required fields or types. Schema validation is always a necessary separate step." },
    "structured-q2": { correctIndex: 1, explanation: "Each repair attempt is its own real LLM call with real cost and latency. Without a maxAttempts cap and a defined fallback for when it's reached, a persistently-invalid model response can trigger far more spend and delay than a single request should ever cause." },
    "structured-q3": { correctIndex: 1, explanation: "Schema validation only confirms shape and type, not business correctness. A model can produce a perfectly well-formed but completely wrong or hallucinated argument value — real-consequence tool calls need domain-specific validation on top of schema validation, every time." },
    "structured-q4": { correctIndex: 1, explanation: "A prompt instruction is a request the model can still fail to follow. Constrained decoding operates at the token-sampling level, intersecting the model's distribution with only the tokens that keep the output grammatically valid — it's a structural guarantee, not a politely-worded hope." },
    "structured-q5": { correctIndex: 2, explanation: "finishReason: 'length' means the response hit the token limit mid-generation — it's a budget problem, not a parsing or prompting problem. The JSON is incomplete because it was cut off, and no amount of lenient parsing or extra examples fixes that; only more budget (or a smaller target output) does." },
  },
};
