import type { ChecklistItem } from "../types";

/** Evals and Security categories. */
export const qualityChecklistItems: ChecklistItem[] = [
  // --- Evals -----------------------------------------------------------------
  {
    id: "checklist-evals-golden-dataset-exists",
    category: "Evals",
    title: "A golden dataset exists before launch, not after the first incident",
    why: "Without a fixed, representative case set, there's no way to measure whether any future change is actually an improvement — every decision becomes a guess.",
    howToVerify: "Confirm a dataset with at least 20-30 representative cases (covering common and edge-case inputs) exists and is referenced by an actual eval run with a stored EvalSuiteResult, not just created and forgotten.",
    severity: "critical",
    moduleId: "evals",
  },
  {
    id: "checklist-evals-ci-regression-gate",
    category: "Evals",
    title: "A regression gate is wired into CI, not just available as a manual dashboard",
    why: "An eval score that a human has to remember to check is a score that will eventually not get checked before a regression ships.",
    howToVerify: "Confirm `/evals/ci-check` (or an equivalent CI script) runs automatically on every prompt/model-affecting change and that a failing threshold actually blocks the merge/deploy, not just posts a warning.",
    severity: "critical",
    moduleId: "evals",
  },
  {
    id: "checklist-evals-judge-validated",
    category: "Evals",
    title: "LLM-judge scores have been validated against human judgment on a sample",
    why: "An unvalidated judge is just another opaque black box — judge biases (verbosity, position, self-enhancement) can make scores look healthy while missing real quality problems.",
    howToVerify: "Pull 20-30 judge-scored cases, have a human independently score them blind, and compute agreement; if agreement is low, revise the rubric or judge model before trusting it to gate deploys.",
    severity: "important",
    moduleId: "evals",
  },
  {
    id: "checklist-evals-position-bias-mitigated",
    category: "Evals",
    title: "Pairwise comparisons are run in both orders to catch position bias",
    why: "Position bias is strong enough to flip a judge's verdict purely based on which response is shown first — an unmitigated pairwise eval can report a 'preference' that's actually just an ordering artifact.",
    howToVerify: "Confirm the pairwise eval pipeline runs each comparison twice with order swapped and flags (or discards) any case where the verdict flips between the two orderings.",
    severity: "important",
    moduleId: "evals",
  },
  {
    id: "checklist-evals-dataset-refreshed",
    category: "Evals",
    title: "The golden dataset is refreshed periodically from real production failures",
    why: "A dataset that was comprehensive at launch quietly loses relevance as real traffic drifts away from what it covers — passing evals stop meaning what they used to mean.",
    howToVerify: "Confirm there's a recurring (e.g. monthly) process that reviews real production failures/edge cases and adds representative new cases to the golden dataset, with a changelog of additions.",
    severity: "nice-to-have",
    moduleId: "evals",
  },
  // --- Security --------------------------------------------------------------
  {
    id: "checklist-security-pii-redacted-before-logging",
    category: "Security",
    title: "PII is redacted before prompts/outputs are logged or stored",
    why: "Raw prompts containing PII sitting in log aggregation systems (with their own broad access lists) is a data exposure risk independent of anything the model itself does.",
    howToVerify: "Send a test request containing a fake email/phone/name through the pipeline and grep the resulting logs/traces to confirm the PII was redacted before it was ever written, not just displayed-redacted in a UI layer.",
    severity: "critical",
    moduleId: "security",
  },
  {
    id: "checklist-security-indirect-injection-reviewed",
    category: "Security",
    title: "Every source of retrieved/tool-sourced content has been reviewed for indirect injection risk",
    why: "Indirect injection hides in documents, web pages, and tool results the application implicitly trusts — a user can trigger it without typing anything malicious themselves.",
    howToVerify: "List every place untrusted external content (documents, scraped pages, tool outputs) enters a prompt, and confirm each is wrapped in clear delimiters and never granted system/developer-level instruction priority.",
    severity: "critical",
    moduleId: "security",
  },
  {
    id: "checklist-security-tool-args-validated",
    category: "Security",
    title: "Tool call arguments are validated against business rules before execution, not just schema-validated",
    why: "A schema-valid tool call can still carry a hallucinated or attacker-manipulated argument value — shape validation alone doesn't catch a nonsensical or malicious amount, account, or action.",
    howToVerify: "For every tool with a real side effect, confirm there's an explicit validation step (range checks, allow-lists, ownership checks) between 'schema passed' and 'tool executed', and that it's covered by a test with a deliberately-wrong argument value.",
    severity: "critical",
    moduleId: "security",
  },
  {
    id: "checklist-security-redteam-pass-run",
    category: "Security",
    title: "A red-team pass has been run against the OWASP LLM Top 10 attack catalog",
    why: "Guardrails that were never actually attacked are guardrails whose real effectiveness is unknown — 'we have a filter' isn't the same as 'we measured what the filter catches.'",
    howToVerify: "Run at least one representative attack per OWASP LLM Top 10 category against the feature (using this app's attack catalog as a template) with guardrails enabled, and confirm/document which layer caught each one.",
    severity: "important",
    moduleId: "security",
  },
  {
    id: "checklist-security-guardrail-changes-audited",
    category: "Security",
    title: "Guardrail configuration changes are audit-logged",
    why: "A guardrail silently loosened (deliberately or by mistake) is invisible until something gets through — without an audit trail, nobody can reconstruct why an attack that should have been blocked wasn't.",
    howToVerify: "Change a guardrail setting and confirm an AuditLogEntry with action 'guardrail.config.update' is written and queryable via the audit-log endpoint, including who/when/what changed.",
    severity: "important",
    moduleId: "security",
  },
];
