import type { ChecklistItem } from "../types";

/** Prompting, Retrieval, and Agents categories. */
export const productChecklistItems: ChecklistItem[] = [
  // --- Prompting ---------------------------------------------------------
  {
    id: "checklist-prompting-versioned",
    category: "Prompting",
    title: "Prompts are versioned, not inline strings",
    why: "An unversioned prompt can't be diffed, rolled back, or tied to the eval result that justified a change — 'it broke sometime last sprint' becomes undebuggable.",
    howToVerify: "Open the prompt in the versioning UI and confirm it has more than one version with a parentVersionId chain; confirm the production feature references a specific version id, not a floating/latest alias.",
    severity: "critical",
    moduleId: "prompting",
  },
  {
    id: "checklist-prompting-injection-safe-template",
    category: "Prompting",
    title: "Untrusted input is never concatenated directly next to instructions",
    why: "Unescaped template interpolation of user or retrieved content is the single most common root cause of successful prompt injection.",
    howToVerify: "Run `/prompting/injection-check` against every template that interpolates user-, document-, or tool-sourced content, and confirm `safe: true` with no findings before shipping.",
    severity: "critical",
    moduleId: "prompting",
  },
  {
    id: "checklist-prompting-change-requires-eval-diff",
    category: "Prompting",
    title: "A prompt change can't merge without an eval score diff",
    why: "Without a required before/after comparison, a 'small wording fix' can silently regress accuracy, tone, or safety behavior with nobody noticing until a user complains.",
    howToVerify: "Run the golden dataset against both the old and new prompt version and attach the score diff to the PR; confirm the CI regression gate actually blocks merges below threshold, don't just eyeball it.",
    severity: "critical",
    moduleId: "evals",
  },
  {
    id: "checklist-prompting-few-shot-bias-reviewed",
    category: "Prompting",
    title: "Few-shot example order and selection have been reviewed for bias",
    why: "Recency/primacy effects mean example order isn't neutral — a poorly ordered or narrowly-selected example set can anchor output onto an unintended pattern.",
    howToVerify: "Run the same prompt with examples reordered/shuffled against the eval set and confirm scores don't swing meaningfully; if they do, the example set needs diversifying.",
    severity: "nice-to-have",
    moduleId: "prompting",
  },
  // --- Retrieval -----------------------------------------------------------
  {
    id: "checklist-retrieval-relevance-measured",
    category: "Retrieval",
    title: "Retrieval relevance is measured, not assumed",
    why: "'It seems to find the right documents' is not a metric — context precision/recall catch silent retrieval degradation long before users complain.",
    howToVerify: "Run a RAG eval suite that reports context precision and context recall on a labeled query set, and confirm both are tracked over time, not measured once at launch.",
    severity: "critical",
    moduleId: "rag",
  },
  {
    id: "checklist-retrieval-index-freshness-tracked",
    category: "Retrieval",
    title: "Index freshness is tracked, so stale documents don't silently get served",
    why: "Editing a source document doesn't update its vectors automatically — without freshness tracking, a correction can be invisible to the RAG pipeline indefinitely.",
    howToVerify: "Pick a recently-updated document, confirm its chunks were re-embedded and re-indexed, and verify a query touching the changed content returns the updated version, not the stale one.",
    severity: "important",
    moduleId: "rag",
  },
  {
    id: "checklist-retrieval-citations-verified",
    category: "Retrieval",
    title: "Citations are spot-checked against actual chunk content",
    why: "A displayed citation that doesn't actually support its claim reintroduces the exact hallucination risk citations are meant to catch.",
    howToVerify: "Sample 20 recent answers with citations and manually confirm each cited chunk's text actually supports the claim it's attached to; track the pass rate as a faithfulness proxy.",
    severity: "important",
    moduleId: "rag",
  },
  {
    id: "checklist-retrieval-embedding-model-pinned",
    category: "Retrieval",
    title: "The embedding model/version is pinned, with a documented re-index procedure",
    why: "Vectors from different embedding model versions are incompatible — an unplanned model upgrade silently corrupts similarity search with no error thrown.",
    howToVerify: "Confirm the embedding model id/version is explicitly pinned in config (not a floating alias), and that a runbook exists for 're-embed the full corpus' if it ever needs to change.",
    severity: "critical",
    moduleId: "embeddings",
  },
  {
    id: "checklist-retrieval-chunking-validated",
    category: "Retrieval",
    title: "Chunk size/overlap was validated against real queries, not left at a default",
    why: "Default chunk sizes are rarely optimal for a specific corpus and query style — they're a starting guess, not a tuned decision.",
    howToVerify: "Compare at least two chunk-size configurations against the retrieval eval set and document which one was chosen and why, with the measured precision/recall difference.",
    severity: "nice-to-have",
    moduleId: "embeddings",
  },
  // --- Agents ----------------------------------------------------------------
  {
    id: "checklist-agents-step-budget-timeout-caps",
    category: "Agents",
    title: "Every agent loop has maxSteps, budgetUsd, and timeoutMs configured",
    why: "Without all three caps, a stuck or misbehaving agent can run indefinitely, burning unbounded cost and latency with no structural stop condition.",
    howToVerify: "Inspect the AgentLimits passed into a production agent run and confirm maxSteps, budgetUsd, and timeoutMs are all set to deliberately-chosen, non-default values — not left unset.",
    severity: "critical",
    moduleId: "agents",
  },
  {
    id: "checklist-agents-dangerous-tools-gated",
    category: "Agents",
    title: "Dangerous tools require human-in-the-loop approval or strict argument validation",
    why: "An injected instruction or an honest model mistake can trigger a legitimate tool's misuse — tools capable of real side effects need a checkpoint beyond the model's own judgment.",
    howToVerify: "List every tool marked dangerous: true in the registry and confirm each one is either in approvalRequiredTools or has argument-level business-rule validation before execution.",
    severity: "critical",
    moduleId: "agents",
  },
  {
    id: "checklist-agents-loop-detection-enabled",
    category: "Agents",
    title: "Loop detection is enabled with a tuned similarity threshold",
    why: "max_steps alone only bounds worst-case cost — it doesn't catch an agent stuck repeating a failing approach early, which wastes budget on guaranteed non-progress.",
    howToVerify: "Confirm LoopDetectionConfig.enabled is true in production agent runs, and that a test run deliberately designed to loop actually terminates with stopReason: 'loop_detected' before exhausting max_steps.",
    severity: "important",
    moduleId: "agents",
  },
  {
    id: "checklist-agents-least-privilege-tools",
    category: "Agents",
    title: "Each agent's tool allow-list is scoped to what the task actually needs",
    why: "Granting every available tool 'just in case' maximizes the blast radius of any single bad decision, whether caused by injection or an honest model error.",
    howToVerify: "For each production agent, list its toolAllowList and confirm every tool is actually required for its stated task — remove any that aren't, and document why each remaining one is needed.",
    severity: "important",
    moduleId: "security",
  },
  {
    id: "checklist-agents-memory-provenance",
    category: "Agents",
    title: "Long-term agent memory has provenance/confidence metadata and a correction path",
    why: "A wrong conclusion stored in memory during an earlier run gets retrieved and trusted indefinitely in later runs unless there's an explicit way to flag or correct it.",
    howToVerify: "Inspect a sample of stored long-term memory entries via `/agents/:id/memory` and confirm each has a source/confidence field, and that a documented process exists for correcting or decaying stale entries.",
    severity: "nice-to-have",
    moduleId: "agents",
  },
];
