import type { ChecklistItem } from "../types";

/** Cost, Reliability, Observability, Data & Privacy, and Rollout categories. */
export const opsChecklistItems: ChecklistItem[] = [
  // --- Cost --------------------------------------------------------------
  {
    id: "checklist-cost-per-request-measured",
    category: "Cost",
    title: "Cost per request is measured and broken down by model/feature",
    why: "A feature that 'seems cheap' can quietly dominate the bill once volume scales — without per-request, per-feature cost visibility, nobody notices until the invoice arrives.",
    howToVerify: "Query `/production/cost-summary` grouped by feature and model, and confirm the numbers are reviewed on a recurring cadence (not just available if someone thinks to look).",
    severity: "critical",
    moduleId: "production",
  },
  {
    id: "checklist-cost-cache-strategy-measured",
    category: "Cost",
    title: "A caching strategy exists, with measured (not assumed) hit rate and savings",
    why: "An assumed cache hit rate borrowed from a blog post routinely diverges from what a specific workload's real query repetition looks like, making cost projections unreliable.",
    howToVerify: "Run `/production/cache-sim` against a representative sample of real recent requests and confirm the reported hit rate and savings are based on actual measured repetition, not an input assumption.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-cost-model-routing-considered",
    category: "Cost",
    title: "Model routing (cheap vs. expensive) has been considered for mixed-complexity workloads",
    why: "Sending every request to the most capable (and most expensive) model regardless of actual complexity leaves cost savings on the table with no quality benefit for the easy cases.",
    howToVerify: "Classify a sample of recent requests by complexity and run `/production/routing-sim`; confirm the team has a documented decision about whether routing is worth the added complexity for this workload.",
    severity: "nice-to-have",
    moduleId: "production",
  },
  {
    id: "checklist-cost-context-trimming-defined",
    category: "Cost",
    title: "Long conversations/contexts have a defined trimming strategy",
    why: "Unbounded context growth in long-running conversations silently increases both cost and latency (via prefill/TTFT) on every single turn, and can eventually overflow the model's context window entirely.",
    howToVerify: "Confirm a context strategy (truncate-oldest, truncate-middle, sliding-window, or summarize) is explicitly configured for any feature with multi-turn conversations, and run `/production/context-trim-sim` to see its measured savings.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-cost-budget-alerts-configured",
    category: "Cost",
    title: "Budget alerts/quotas are configured, not just rate limits",
    why: "Rate limiting prevents short-term bursts, but a client staying comfortably under the rate limit can still burn through a monthly budget far faster than intended — only a quota catches that.",
    howToVerify: "Confirm a daily/monthly spend quota is configured per feature or per API key, with an alert that fires before the hard cap is hit, not only at 100%.",
    severity: "important",
    moduleId: "production",
  },
  // --- Reliability ---------------------------------------------------------
  {
    id: "checklist-reliability-retries-have-idempotency",
    category: "Reliability",
    title: "Every retried write operation has an idempotency key",
    why: "A timeout doesn't tell you whether the original request actually succeeded — retrying a non-idempotent write (charge, send, create) on an ambiguous failure risks executing it twice.",
    howToVerify: "Trigger `/production/reliability-sim` with scenario 'duplicate-request' and confirm the replayed request returns outcome 'deduplicated' rather than re-executing the operation.",
    severity: "critical",
    moduleId: "production",
  },
  {
    id: "checklist-reliability-circuit-breaker",
    category: "Reliability",
    title: "A circuit breaker protects against sustained provider outages",
    why: "Retry-with-backoff alone keeps hammering a dependency that's completely down, adding load to a struggling system instead of giving it room to recover.",
    howToVerify: "Trigger `/production/reliability-sim` with scenario 'provider-down' and confirm the configured policy actually stops sending requests after the threshold, rather than retrying indefinitely.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-reliability-fallback-provider",
    category: "Reliability",
    title: "A fallback provider/model is configured for critical features",
    why: "A single-provider dependency means any outage or rate-limit event on that provider takes the entire feature down with it, with no path to degrade gracefully.",
    howToVerify: "Confirm `fallbackProviderId` (or equivalent) is set for any feature whose downtime would be user-visible, and test that a simulated primary-provider failure actually falls through to the secondary.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-reliability-bounded-queue",
    category: "Reliability",
    title: "Request queues have a bounded depth with explicit load-shedding",
    why: "An unbounded queue doesn't prevent overload, it just delays it — and risks exhausting memory — instead of failing fast once capacity is genuinely exceeded.",
    howToVerify: "Trigger `/production/reliability-sim` with scenario 'queue-backpressure' at a concurrency below the simulated load, and confirm excess requests get outcome 'queued' up to a cap, with a clear rejection beyond it.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-reliability-timeout-budgets",
    category: "Reliability",
    title: "Every external call (provider, vector store, tool) has an explicit timeout",
    why: "Without a timeout budget, a single slow dependency can hang a request indefinitely, and that hang compounds badly in an agent loop with multiple sequential calls.",
    howToVerify: "List every external call a feature makes and confirm each one has a configured timeout shorter than the feature's own end-to-end latency budget, not an unbounded default.",
    severity: "critical",
    moduleId: "production",
  },
  // --- Observability --------------------------------------------------------
  {
    id: "checklist-observability-every-call-is-a-run",
    category: "Observability",
    title: "Every LLM call is persisted as an inspectable Run",
    why: "Without a stored record of params, usage, cost, latency, and output per call, debugging a bad production answer means guessing — there's no way to see what actually happened.",
    howToVerify: "Trigger a representative request and confirm a Run row exists via `GET /runs/:id` with populated params, usage, cost, and latencyMs — before and not only after something goes wrong.",
    severity: "critical",
    moduleId: "production",
  },
  {
    id: "checklist-observability-traces-linked",
    category: "Observability",
    title: "Nested calls (RAG stages, agent steps, judge calls) are linked in one trace",
    why: "A multi-step feature's cost/latency is meaningless as one aggregate number — you need to see which specific sub-call drove a slow or expensive request.",
    howToVerify: "Run a multi-step feature (RAG query, agent run, or eval with a judge) and confirm `GET /traces/:id` shows the full parent/child span structure, not just a flat list of unrelated calls.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-observability-ttft-vs-tokens-per-sec",
    category: "Observability",
    title: "TTFT and tokens/sec are tracked as separate metrics, not collapsed into one 'response time'",
    why: "TTFT (prefill-bound) and decode throughput (sequential, tokens/sec) are driven by different bottlenecks — a single blended latency number hides which one actually needs fixing.",
    howToVerify: "Confirm the latency dashboard reports TTFT and tokens/sec as distinct tracked metrics (p50/p95 each), not a single averaged 'response time'.",
    severity: "nice-to-have",
    moduleId: "production",
  },
  {
    id: "checklist-observability-cost-error-alerting",
    category: "Observability",
    title: "Alerting exists for cost and error-rate anomalies, not just uptime",
    why: "A feature can be 'up' (200 responses) while silently producing garbage output or costing 10x normal — uptime monitoring alone misses both.",
    howToVerify: "Confirm an alert fires on a sudden error-rate or per-request-cost spike relative to a rolling baseline, independent of whether the service itself reports healthy.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-observability-pii-safe-logging-verified",
    category: "Observability",
    title: "Logging has been verified to be PII-safe, not just assumed to be",
    why: "A redaction rule that works in testing can still miss real-world PII shapes (names in prose, regional phone formats) that weren't in the test cases.",
    howToVerify: "Run a batch of real (or realistic synthetic) requests containing varied PII shapes through the pipeline and manually audit the resulting logs for anything that leaked through.",
    severity: "critical",
    moduleId: "security",
  },
  // --- Data & Privacy ---------------------------------------------------------
  {
    id: "checklist-privacy-redaction-verified-end-to-end",
    category: "Data & Privacy",
    title: "PII redaction is verified end-to-end, not just at the regex layer",
    why: "Pattern-based redaction misses context-dependent PII (a name embedded in a sentence, an uncommon ID format) that a human reviewer would catch instantly but a naive regex won't.",
    howToVerify: "Combine pattern-based checks with a sampled human or model-based review of real logged content, and track the miss rate as an ongoing metric, not a one-time pass/fail.",
    severity: "critical",
    moduleId: "security",
  },
  {
    id: "checklist-privacy-retention-policy-defined",
    category: "Data & Privacy",
    title: "A data retention policy is defined for stored prompts, outputs, and traces",
    why: "Indefinitely retaining every prompt/response/trace is both a growing storage cost and an expanding privacy liability — 'we never delete anything' isn't a policy, it's an accident waiting to surface.",
    howToVerify: "Confirm a documented retention period exists for Runs/Traces and that an actual deletion job (not just a plan) enforces it.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-privacy-provider-terms-reviewed",
    category: "Data & Privacy",
    title: "Third-party provider data-handling terms have been reviewed for this use case",
    why: "Whether a provider retains, trains on, or shares submitted data varies by provider and plan — sending sensitive data through a provider whose terms don't match your requirements is a compliance risk discovered too late.",
    howToVerify: "Check the current provider documentation (terms change — don't rely on memory) for data retention/training-use policy for the specific plan/endpoint in use, and confirm it matches your data-sensitivity requirements.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-privacy-sensitive-docs-excluded-from-finetuning",
    category: "Data & Privacy",
    title: "Sensitive documents are excluded from any fine-tuning or synthetic-data pipeline without explicit consent",
    why: "A fine-tuning dataset built from real user interactions can memorize and later regurgitate sensitive content if sensitive documents weren't explicitly filtered out first.",
    howToVerify: "Audit the fine-tuning/synthetic-data source pipeline and confirm there's an explicit filter or consent check excluding sensitive documents, not just an assumption that 'the training set is fine.'",
    severity: "important",
    moduleId: "advanced",
  },
  {
    id: "checklist-privacy-document-access-controls",
    category: "Data & Privacy",
    title: "Access controls on retrieved document sources match the querying user's actual permissions",
    why: "A RAG system that retrieves from a shared index without per-user access filtering can leak one user's private documents into another user's answer.",
    howToVerify: "Test retrieval as two different simulated users with different document access, and confirm neither ever sees chunks from documents they shouldn't have access to.",
    severity: "critical",
    moduleId: "rag",
  },
  // --- Rollout -----------------------------------------------------------------
  {
    id: "checklist-rollout-canary-with-rollback-trigger",
    category: "Rollout",
    title: "A canary plan exists with an explicit, pre-defined rollback trigger",
    why: "A canary that nobody is actually watching, with no defined 'roll it back if X happens' trigger, provides a false sense of safety without real protection.",
    howToVerify: "Confirm the canary rollout plan names specific metrics and thresholds (error rate, cost per request, eval score) that trigger an automatic or immediate manual rollback, not just 'we'll keep an eye on it.'",
    severity: "critical",
    moduleId: "production",
  },
  {
    id: "checklist-rollout-shadow-before-canary",
    category: "Rollout",
    title: "Shadow testing runs before canarying a model/prompt change",
    why: "Shadowing catches real-traffic-input issues with zero user-facing risk before exposing any real users to a canary — skipping it means the canary is the first real-traffic test.",
    howToVerify: "Confirm the new version was run in shadow mode against recent real traffic and its outputs were compared to production before any canary traffic was routed to it.",
    severity: "important",
    moduleId: "production",
  },
  {
    id: "checklist-rollout-model-version-pinned",
    category: "Rollout",
    title: "The model/version in use is explicitly pinned, not a floating 'latest' alias",
    why: "A provider silently updating a model behind a 'latest' alias can change behavior on your exact prompts with zero code change on your side — this is model drift you didn't choose.",
    howToVerify: "Confirm the exact model identifier used in production is a specific pinned version (check current provider docs for the exact available ids), and that upgrading it is a deliberate, tested action, not an automatic side effect of a provider update.",
    severity: "critical",
    moduleId: "production",
  },
  {
    id: "checklist-rollout-deprecation-plan",
    category: "Rollout",
    title: "Retired prompt/model versions have a documented deprecation plan",
    why: "Old prompt versions and model ids referenced by stored EvalSuiteResults or PromptVersions can't just be deleted — without a plan, deprecation becomes an ad hoc mess that breaks historical comparisons.",
    howToVerify: "Confirm there's a documented process for marking a prompt/model version deprecated (not deleted) while preserving referential integrity for historical eval results and audit logs.",
    severity: "nice-to-have",
    moduleId: "production",
  },
  {
    id: "checklist-rollout-postmortem-process",
    category: "Rollout",
    title: "A postmortem process exists for production regressions",
    why: "Without a structured postmortem, the same class of regression (a bad prompt change, a provider drift, a missing guardrail) tends to recur because the root cause was never captured and fed back into the checklist/eval set.",
    howToVerify: "Confirm the last production LLM-related incident has a written postmortem that includes a concrete fix fed back into either the golden dataset, this checklist, or the CI regression gate.",
    severity: "nice-to-have",
    moduleId: "production",
  },
];
