import type { GlossaryTerm } from "../types";

export const agentsTerms: GlossaryTerm[] = [
  {
    id: "agent-loop",
    term: "Agent Loop",
    short: "The repeated cycle of an agent observing state, deciding an action (often a tool call), executing it, and incorporating the result before deciding again.",
    long: "The agent loop is the generalization of the ReAct pattern into a production control structure: at each iteration the model receives the accumulated history (including prior tool results) and either calls another tool or produces a final answer, with the loop bounded by explicit limits (max steps, budget, timeout) rather than left open-ended. Every agent reliability problem — runaway cost, infinite loops, wrong tool chosen repeatedly — traces back to this loop lacking a sufficient stop condition, which is why production agent frameworks treat step/budget/timeout limits as mandatory, not optional, configuration.",
    related: ["react-pattern", "loop-detection", "agent-planning", "tool-calling"],
    moduleId: "agents",
  },
  {
    id: "agent-planning",
    term: "Agent Planning",
    short: "An agent explicitly decomposing a goal into an ordered sequence of sub-steps before (or while) executing them.",
    long: "Planning can be done upfront (produce a full plan, then execute it step by step) or interleaved with execution (replan after each observation, which is more robust to surprises but costs more LLM calls). Upfront plans are more predictable and easier to show a human for approval, but they can become stale or wrong the moment reality diverges from the plan's assumptions — a classic failure where the agent keeps executing an outdated plan rather than noticing it needs to replan.",
    related: ["agent-loop", "reflection", "supervisor-worker-pattern"],
    moduleId: "agents",
  },
  {
    id: "reflection",
    term: "Reflection (Self-Critique)",
    short: "An agent evaluating its own prior output or action and revising its approach based on that self-assessment.",
    long: "Reflection adds a dedicated step where the model critiques its own intermediate work ('did this tool result actually answer the sub-goal? what should I try differently?') before continuing, which can catch errors a single forward pass would have missed. It costs an extra LLM call per reflection and is not a guaranteed fix — a model can reflect confidently and incorrectly conclude its wrong answer was right, so reflection improves average-case robustness without providing a correctness guarantee.",
    related: ["agent-loop", "agent-planning"],
    moduleId: "agents",
  },
  {
    id: "supervisor-worker-pattern",
    term: "Supervisor/Worker (Orchestrator) Pattern",
    short: "A top-level agent that decomposes a goal and delegates sub-tasks to specialized worker agents, then integrates their results.",
    long: "This pattern mirrors human team structures: the supervisor holds the overall goal and routing logic, while workers are narrower, often cheaper or more specialized agents focused on one kind of sub-task (a research worker, a coding worker, a verification worker). It trades additional orchestration complexity and inter-agent communication overhead for better separation of concerns and the ability to use different models/tools per worker — not worth the complexity for simple tasks a single agent loop handles fine.",
    related: ["agent-planning", "agent-loop"],
    moduleId: "agents",
  },
  {
    id: "short-term-memory",
    term: "Short-Term (Working) Memory",
    short: "The agent's in-context conversation/scratchpad state for the current run — everything currently in the prompt.",
    long: "Short-term memory is bounded by the context window and disappears once the run ends unless explicitly persisted elsewhere; it is simply 'what's currently in the messages array', including tool results and intermediate reasoning for this run. Long-running agents that exceed the context window need an explicit strategy (summarization, truncation, or offloading to long-term memory) for what stays in working memory versus what gets dropped or externalized — this is the same context-management problem as M1's context-window strategies, applied inside an agent loop.",
    related: ["long-term-memory", "context-window", "episodic-memory"],
    moduleId: "agents",
  },
  {
    id: "long-term-memory",
    term: "Long-Term Memory",
    short: "Persistent storage (often a vector store) that an agent can write to and query across runs, outliving any single context window.",
    long: "Long-term memory is typically implemented as embedded facts/summaries stored in a vector database and retrieved via similarity search when relevant to the current task — functionally RAG, but over the agent's own accumulated experience rather than a fixed document corpus. It introduces a new failure mode specific to agents: memory can accumulate stale, contradictory, or simply wrong 'facts' from earlier mistaken runs, which then get retrieved and trusted in later runs unless there's an explicit mechanism to verify, decay, or correct stored memories.",
    related: ["short-term-memory", "episodic-memory", "vector-database"],
    moduleId: "agents",
  },
  {
    id: "episodic-memory",
    term: "Episodic Memory",
    short: "An agent's record of specific past events/runs/interactions, as distinct from general long-term factual memory.",
    long: "Episodic memory stores 'what happened' (this specific run, this specific user interaction, this specific tool-call outcome) rather than generalized knowledge, which is useful for an agent that needs to recall its own history of attempts (e.g. 'I already tried this approach and it failed because X'). The distinction from long-term semantic memory matters in system design: episodic entries are naturally timestamped and often should be weighted toward recency or explicitly superseded, whereas general factual memory is not inherently time-ordered.",
    related: ["long-term-memory", "short-term-memory"],
    moduleId: "agents",
  },
  {
    id: "loop-detection",
    term: "Loop Detection",
    short: "A guardrail that monitors an agent's recent steps for repetition (near-identical actions/results) and halts the run if detected.",
    long: "Loop detection typically compares recent steps within a sliding window using a similarity threshold — if the agent is repeatedly calling the same tool with near-identical arguments and getting near-identical results, it is almost certainly stuck, not making progress, and should be stopped rather than left to burn through its step/budget limit doing nothing useful. This is a distinct safety net from max-steps: max-steps bounds total cost even on healthy-looking progress, while loop detection catches pathological non-progress earlier and cheaper.",
    related: ["agent-loop", "human-in-the-loop"],
    moduleId: "agents",
  },
  {
    id: "human-in-the-loop",
    term: "Human-in-the-Loop (HITL)",
    short: "Pausing an agent before a designated class of actions (e.g. anything 'dangerous') to require explicit human approval before proceeding.",
    long: "HITL is the strongest practical safeguard against an agent taking an irreversible or high-stakes action (sending money, deleting data, sending an external email) based on a misjudgment, because it inserts a verification point a purely automated guardrail cannot replace. Implementing it correctly requires the agent's execution to genuinely pause and resume state correctly (not just log a warning and continue) and a clear, fast approval UX — a HITL gate that routinely times out or gets rubber-stamped without real review provides much weaker protection than the architecture diagram suggests.",
    related: ["loop-detection", "agent-loop", "least-privilege"],
    moduleId: "agents",
  },
  {
    id: "model-context-protocol",
    term: "Model Context Protocol (MCP)",
    short: "An open protocol for exposing tools, resources, and prompts from external servers to LLM applications in a standardized way.",
    long: "MCP decouples 'what tools exist and how to call them' from any single application's bespoke tool-definition format, letting a tool server built once be reused across multiple agent frameworks/applications that all speak the protocol, analogous to how a REST API decouples a backend from any one frontend. In practice this means an agent can discover and call tools from an MCP server it has never specifically been coded against, which is powerful but also means the security model (what the server is allowed to do, what it returns, whether it can be trusted) needs the same allow-listing and sandboxing scrutiny as any other externally-sourced tool.",
    related: ["tool-calling", "tool-registry", "allow-list"],
    moduleId: "agents",
  },
  {
    id: "tool-registry",
    term: "Tool Registry",
    short: "The catalog of tools (name, description, parameter schema, danger classification) an agent is allowed to see and call.",
    long: "The registry is the actual security boundary for an agent, more so than any prompt-level instruction: an agent literally cannot call a tool that isn't in its registry/allow-list for that run, regardless of what the model 'wants' to do. Marking tools `dangerous: true` (filesystem access, code execution, network fetch) and gating them behind human-in-the-loop approval is the registry-level enforcement of least privilege — don't rely on the system prompt alone to say 'don't use the dangerous tool without asking'.",
    related: ["least-privilege", "allow-list", "human-in-the-loop", "sandboxing"],
    moduleId: "agents",
  },
];
