import type { GlossaryTerm } from "../types";

export const embeddingsVectorTerms: GlossaryTerm[] = [
  {
    id: "embedding",
    term: "Embedding",
    short: "A dense numeric vector representing the semantic meaning of text (or another modality) in a continuous space.",
    long: "Embeddings are trained so that semantically similar inputs land close together in vector space under some distance metric, which is what makes similarity search possible at all. A critical, often-missed detail: embeddings from different models (or even different versions of the same model) live in incompatible spaces — you cannot mix vectors from two different embedding models in one index or compare them meaningfully, and re-embedding your entire corpus is required whenever you switch embedding models.",
    related: ["cosine-similarity", "vector-database", "embedding-dimension", "approximate-nearest-neighbor"],
    moduleId: "embeddings",
  },
  {
    id: "embedding-dimension",
    term: "Embedding Dimension",
    short: "The length of the vector an embedding model produces.",
    long: "Higher dimensionality generally captures more nuance but costs more storage and compute for every downstream similarity computation and index build, so embedding dimension is a real production cost lever, not just a model detail. Some providers offer dimension-truncation or purpose-built smaller variants of the same embedding model specifically to let you trade a small amount of retrieval quality for significantly lower storage/compute cost at scale.",
    related: ["embedding", "vector-database"],
    moduleId: "embeddings",
  },
  {
    id: "cosine-similarity",
    term: "Cosine Similarity",
    short: "The cosine of the angle between two vectors — measures orientation similarity, ignoring magnitude.",
    long: "Cosine similarity is the default metric for most text embeddings because many embedding models are trained (or normalized) specifically so that direction, not magnitude, carries the semantic signal; using a magnitude-sensitive metric like raw dot product on non-normalized embeddings can give misleading rankings. Always check what distance metric an embedding model was trained/recommended for — using the wrong metric against the right vectors silently degrades retrieval quality without throwing any error.",
    related: ["dot-product-similarity", "euclidean-distance", "embedding"],
    moduleId: "embeddings",
  },
  {
    id: "dot-product-similarity",
    term: "Dot Product Similarity",
    short: "The sum of elementwise products of two vectors — equivalent to cosine similarity scaled by both vectors' magnitudes.",
    long: "Dot product is cheaper to compute than cosine similarity (no normalization step) and is mathematically identical to cosine similarity when all vectors are pre-normalized to unit length, which is exactly what many vector databases do internally for performance — store normalized vectors once, then use the cheaper dot product at query time. If your embeddings are not normalized and your vector store's 'dot product' index assumes they are, retrieval quality degrades silently; check the store's documented assumption.",
    related: ["cosine-similarity", "embedding"],
    moduleId: "embeddings",
  },
  {
    id: "euclidean-distance",
    term: "Euclidean Distance (L2)",
    short: "The straight-line distance between two vectors in their embedding space.",
    long: "L2 distance is sensitive to both direction and magnitude, which makes it a meaningful choice for embeddings that are not normalized or where magnitude itself encodes information (less common for text, more common in some image/multimodal embeddings). For most sentence/document text embeddings, cosine similarity is the recommended and tested metric — using L2 against a model trained/validated for cosine is a frequent and easy-to-miss retrieval-quality bug.",
    related: ["cosine-similarity", "embedding"],
    moduleId: "embeddings",
  },
  {
    id: "approximate-nearest-neighbor",
    term: "Approximate Nearest Neighbor (ANN) Search",
    short: "Finding vectors that are very likely (but not guaranteed) to be among the true k-nearest-neighbors, far faster than exhaustive search.",
    long: "Exact nearest-neighbor search is a brute-force comparison against every vector in the index, which does not scale past roughly tens of thousands of vectors at interactive latency; ANN algorithms (HNSW, IVF, and others) build an index structure that prunes most of the search space at the cost of occasionally missing the true best match. Every ANN method exposes a recall/latency trade-off knob — tuning it is a real production decision, not a one-time default, and should be measured against your actual corpus and query distribution.",
    related: ["hnsw", "ivf", "flat-index", "vector-database"],
    moduleId: "embeddings",
  },
  {
    id: "hnsw",
    term: "HNSW (Hierarchical Navigable Small World)",
    short: "A graph-based ANN index that builds layered graphs of vectors, letting search 'zoom in' from coarse to fine.",
    long: "HNSW is the most widely used general-purpose ANN algorithm in modern vector databases (including Qdrant) because it offers strong recall/latency trade-offs without needing a training/clustering step up front, at the cost of higher memory usage (the graph structure itself) and slower, more expensive index-build/insert operations than simpler structures. Its main tunable parameters (ef_construction, ef_search, M) trade index build time and memory for search accuracy and speed — defaults are rarely optimal for a specific corpus size and query pattern.",
    related: ["approximate-nearest-neighbor", "ivf", "flat-index"],
    moduleId: "embeddings",
  },
  {
    id: "ivf",
    term: "IVF (Inverted File Index)",
    short: "An ANN method that clusters vectors into partitions (via k-means) and searches only the nearest few partitions at query time.",
    long: "IVF requires a training step (clustering the vector space) before it can index data, and its accuracy depends heavily on how many partitions you search per query (nprobe) — searching more partitions improves recall but approaches the cost of exhaustive search. It generally uses less memory than HNSW for comparable recall at large scale, which makes it attractive for very large, mostly-static corpora, but it adapts less gracefully to a continuously growing/changing dataset than graph-based methods.",
    related: ["approximate-nearest-neighbor", "hnsw", "product-quantization"],
    moduleId: "embeddings",
  },
  {
    id: "flat-index",
    term: "Flat (Exhaustive) Index",
    short: "An index that performs brute-force, exact comparison against every stored vector — no approximation.",
    long: "Flat indexes guarantee perfect recall (they cannot miss the true nearest neighbor by construction) and are the right baseline to measure any ANN method's recall loss against, but query latency scales linearly with corpus size, making them impractical for large collections in production. For small collections (a few thousand vectors) or for correctness-testing an ANN configuration, flat search is often the simplest, most defensible choice.",
    related: ["approximate-nearest-neighbor", "hnsw", "ivf"],
    moduleId: "embeddings",
  },
  {
    id: "product-quantization",
    term: "Product Quantization (PQ)",
    short: "Compressing vectors by splitting them into sub-vectors and replacing each sub-vector with a small learned codebook index.",
    long: "PQ dramatically reduces the memory footprint of a vector index (often an order of magnitude) by storing compact codes instead of full-precision floats, which is essential once a corpus grows into the hundreds of millions of vectors and raw float storage becomes the bottleneck. The cost is approximation error on top of whatever approximation the ANN algorithm itself already introduces (PQ is often layered on top of IVF, e.g. 'IVF-PQ'), so recall should be measured end-to-end on your real data, not assumed from either component's isolated specs.",
    related: ["ivf", "approximate-nearest-neighbor"],
    moduleId: "embeddings",
  },
  {
    id: "bm25",
    term: "BM25",
    short: "A classic lexical ranking function that scores documents by term-frequency and inverse-document-frequency, with length normalization.",
    long: "BM25 is a statistical, keyword-based retrieval method with no learned embeddings at all — it excels at exact-term matches (product codes, rare proper nouns, acronyms) that dense embedding search can actually miss because an embedding model has 'smoothed over' exact wording in favor of semantic similarity. This complementary failure profile is exactly why hybrid search (BM25 + vector, fused) consistently outperforms either method alone on real-world corpora with a mix of keyword-sensitive and semantic queries.",
    related: ["hybrid-search", "reciprocal-rank-fusion", "embedding"],
    moduleId: "embeddings",
  },
  {
    id: "hybrid-search",
    term: "Hybrid Search",
    short: "Combining lexical (BM25) and dense vector search, then fusing their result lists into one ranking.",
    long: "Hybrid search exists because BM25 and dense vector search fail on different query types — BM25 struggles with paraphrases and synonyms, dense search struggles with rare exact tokens and out-of-distribution terms — so running both and merging results covers more of the query distribution than either alone. The fusion step (commonly Reciprocal Rank Fusion) matters as much as the two underlying retrievers; a naive score-average fusion is unreliable because BM25 and cosine-similarity scores are not on comparable scales.",
    related: ["bm25", "reciprocal-rank-fusion", "embedding"],
    moduleId: "embeddings",
  },
  {
    id: "reciprocal-rank-fusion",
    term: "Reciprocal Rank Fusion (RRF)",
    short: "A fusion method that scores each document by the sum of 1/(k + rank) across multiple ranked result lists.",
    long: "RRF sidesteps the scale-incompatibility problem of fusing BM25 scores with cosine-similarity scores by using only each list's rank position, not its raw score — a document ranked #1 in either list contributes the same regardless of how differently BM25 and vector search compute their underlying scores. The constant k dampens the influence of rank differences at the tail (default values are typically small integers like 60), and it is a tunable knob worth exposing in any hybrid-search lab rather than hardcoding.",
    related: ["hybrid-search", "bm25"],
    moduleId: "embeddings",
  },
  {
    id: "reranking",
    term: "Reranking",
    short: "A second-stage model that re-scores an initial candidate set of retrieved results with a more expensive, more accurate relevance model.",
    long: "Rerankers (typically cross-encoders) are too slow/expensive to run against an entire corpus, so the standard pattern is: cheap retrieval (vector/BM25/hybrid) pulls a broad candidate set (e.g. top 50-100), then the reranker scores only that smaller set against the actual query for a much more accurate final ordering. This two-stage 'retrieve then rerank' pattern consistently improves top-k precision over single-stage retrieval alone and is one of the highest-leverage, lowest-architectural-risk upgrades to a mediocre RAG pipeline.",
    related: ["cross-encoder", "bi-encoder", "hybrid-search"],
    moduleId: "embeddings",
  },
  {
    id: "cross-encoder",
    term: "Cross-Encoder",
    short: "A model that takes a query and a candidate document together as one input and outputs a single relevance score.",
    long: "Because a cross-encoder processes the query and document jointly (full attention between every query token and every document token), it captures fine-grained interaction that a bi-encoder's separately-computed vectors cannot, which is why cross-encoders are more accurate for relevance scoring. The trade-off is that a cross-encoder cannot be precomputed or indexed — every query-document pair must be scored at query time — so it is only feasible against a small candidate set, never the full corpus.",
    related: ["bi-encoder", "reranking"],
    moduleId: "embeddings",
  },
  {
    id: "bi-encoder",
    term: "Bi-Encoder",
    short: "A model that encodes queries and documents independently into the same vector space, enabling precomputation and fast similarity search.",
    long: "Bi-encoders are what make large-scale semantic search practical at all: documents are embedded once, offline, and stored in an index; only the query needs to be embedded at request time, then compared via a cheap vector-similarity operation against millions of precomputed document vectors. The cost of this efficiency is that query and document never actually attend to each other during encoding, so bi-encoders systematically miss some fine-grained relevance signal that a cross-encoder would catch — hence the common retrieve-with-bi-encoder, rerank-with-cross-encoder pipeline.",
    related: ["cross-encoder", "embedding", "reranking"],
    moduleId: "embeddings",
  },
  {
    id: "vector-database",
    term: "Vector Database",
    short: "A data store purpose-built to index and query high-dimensional vectors via similarity search, usually alongside metadata filters.",
    long: "Vector databases add what a plain ANN library doesn't: durability, CRUD operations, metadata filtering combined with vector search, multi-tenancy/collections, and operational tooling (backups, replication). The interface-level choice to abstract behind a `VectorStore` interface (as this app does, with an in-memory default and Qdrant as a real backend) is what lets a RAG pipeline run with zero setup in development and swap to a production-grade store without changing application code — a pattern worth replicating in real systems.",
    related: ["approximate-nearest-neighbor", "hnsw", "embedding"],
    moduleId: "embeddings",
  },
];
