import type { GlossaryTerm } from "../types";

export const productionTerms: GlossaryTerm[] = [
  {
    id: "observability",
    term: "Observability (LLM systems)",
    short: "The ability to understand what an LLM application is doing in production — every call's inputs, outputs, cost, latency, and trace relationships.",
    long: "LLM observability extends standard distributed-tracing practice with content-specific fields: prompts, completions, token usage, cost, model/provider, and chained-call relationships (a RAG query's retrieval stage, generation stage, and any nested judge calls all belonging to one trace). Without it, debugging a bad production output means guessing, because the only way to know why a specific answer was wrong is to see the actual prompt, actual retrieved context, and actual model parameters for that specific run — generic aggregate dashboards cannot answer 'why did this one request fail'.",
    related: ["opentelemetry-span"],
    moduleId: "production",
  },
  {
    id: "opentelemetry-span",
    term: "OpenTelemetry Span",
    short: "A single named, timed unit of work in a distributed trace, with attributes and parent/child relationships to other spans.",
    long: "OTel gives LLM applications a vendor-neutral way to represent nested operations — an agent run as a root span, each tool call and each nested LLM call as child spans — so a single trace viewer can show the full causal chain of a complex request regardless of which backend/exporter is used. Instrumenting LLM-specific attributes (model, token counts, cost) as span attributes, rather than inventing a parallel logging system, is what lets you reuse existing tracing tooling (dashboards, alerting, sampling) instead of building bespoke observability from scratch.",
    related: ["observability"],
    moduleId: "production",
  },
  {
    id: "prompt-caching",
    term: "Prompt Caching",
    short: "Reusing the computed KV-cache state of a previously-seen prompt prefix so a repeated prefix doesn't need to be reprocessed.",
    long: "Prompt caching targets a very specific, common pattern — a large, stable prefix (system prompt, few-shot examples, a big retrieved document) followed by a small varying suffix (the actual user turn) — and can meaningfully cut both cost and TTFT for that pattern specifically, because the model only has to prefill the new suffix tokens, not the whole prompt. It only helps when the cached prefix is byte-for-byte identical across calls; even a single changed character anywhere in the 'stable' prefix invalidates the cache for that request, so cache-friendly prompt design means putting genuinely static content first and variable content last.",
    related: ["kv-cache", "semantic-caching", "response-caching", "time-to-first-token"],
    moduleId: "production",
  },
  {
    id: "semantic-caching",
    term: "Semantic Caching",
    short: "Caching responses keyed by embedding similarity to a past query, so a differently-worded but semantically equivalent request can reuse a prior answer.",
    long: "Unlike exact-match response caching, semantic caching can hit even when the new query is phrased differently from any prior cached query, which is valuable for high-traffic FAQ-style workloads with huge lexical variety but limited actual distinct intents. The risk is false-positive hits: two queries can be embedding-similar yet require meaningfully different answers (different specifics, different time-sensitivity), so a similarity threshold that's too loose serves wrong-but-plausible cached answers — this needs to be tuned and monitored, not just set once.",
    related: ["prompt-caching", "response-caching", "embedding", "cosine-similarity"],
    moduleId: "production",
  },
  {
    id: "response-caching",
    term: "Response Caching",
    short: "Storing and reusing a complete prior response for an exact-match (or normalized-match) repeated request.",
    long: "Response caching is the simplest and cheapest of the three caching layers (prompt, semantic, response) because it requires no embedding computation and no partial-reuse logic — just a key lookup — but it only helps for genuinely repeated requests, which is a minority of traffic in many conversational applications where every user turn is unique. It is most valuable for deterministic, high-repeat-rate workloads (classification, lookups, common FAQ answers), less valuable for open-ended chat.",
    related: ["prompt-caching", "semantic-caching"],
    moduleId: "production",
  },
  {
    id: "model-routing",
    term: "Model Routing",
    short: "Dynamically selecting which model to use for a given request based on complexity, cost target, or fallback need.",
    long: "Routing strategies range from static rules (cheap model for classification-style requests, expensive model for open-ended reasoning) to complexity-classifiers that score each request before choosing a model, to fallback chains that escalate to a stronger (or different-provider) model only when a cheaper attempt fails or is rejected. The measurable win is real cost reduction without a proportional quality loss, but it requires having an actual way to estimate request complexity or detect failure — a routing strategy that misclassifies complexity will either overpay on easy requests or underperform on hard ones.",
    related: ["request-batching", "quota", "cost-per-token"],
    moduleId: "production",
  },
  {
    id: "request-batching",
    term: "Request Batching",
    short: "Grouping multiple independent requests into a single provider call (or a tightly pipelined set of calls) to amortize fixed overhead.",
    long: "Batching reduces per-request fixed costs (connection overhead, and on self-hosted inference, better GPU utilization from larger batch sizes) but introduces a latency/throughput trade-off: a request has to wait for its batch to fill (or a timeout to fire) before processing starts, which raises the latency floor for any individual request in exchange for better aggregate throughput and often lower aggregate cost. It is a better fit for asynchronous or background workloads than for latency-sensitive interactive chat.",
    related: ["model-routing", "queueing"],
    moduleId: "production",
  },
  {
    id: "retry-with-backoff",
    term: "Retry with Backoff",
    short: "Automatically retrying a failed request after a delay that increases (often exponentially) with each successive failure.",
    long: "Backoff prevents a transient provider issue (a brief rate limit, a momentary 5xx) from being made worse by an immediate retry storm hitting the same struggling endpoint; exponential backoff with jitter (randomizing the delay slightly) additionally prevents many clients from retrying in synchronized waves that re-create the overload they're trying to recover from. Retries must be paired with idempotency for any request with side effects — blindly retrying a non-idempotent 'charge the user' or 'send the email' call on an ambiguous failure (timeout, where the first attempt may have actually succeeded) can cause duplicate side effects.",
    related: ["circuit-breaker", "idempotency-key", "rate-limiting"],
    moduleId: "production",
  },
  {
    id: "circuit-breaker",
    term: "Circuit Breaker",
    short: "A pattern that stops sending requests to a failing dependency for a cooldown period once failures exceed a threshold, instead of retrying indefinitely.",
    long: "A circuit breaker protects both the caller (stop wasting latency/cost on a dependency that's clearly down) and the struggling dependency itself (stop adding load to a system that's already failing, giving it room to recover) — it is the structural complement to retry-with-backoff, which handles isolated transient failures, while the breaker handles sustained outages. After the cooldown, breakers typically allow a small number of 'trial' requests through (half-open state) to detect recovery before fully reopening traffic.",
    related: ["retry-with-backoff", "rate-limiting"],
    moduleId: "production",
  },
  {
    id: "idempotency-key",
    term: "Idempotency Key",
    short: "A client-supplied unique identifier for a request, letting the server recognize and safely ignore duplicate submissions of the same logical operation.",
    long: "Idempotency keys solve the ambiguous-timeout problem: if a request times out, the client doesn't actually know whether the server received and processed it or not, and retrying blindly risks a duplicate side effect (double charge, duplicate send). By tagging the retry with the same idempotency key as the original attempt, the server can recognize 'I've already handled this exact operation' and return the original result instead of re-executing it — this requires the server to persist a record of handled keys for some retention window, not just a stateless retry.",
    related: ["retry-with-backoff"],
    moduleId: "production",
  },
  {
    id: "canary-deployment",
    term: "Canary Deployment",
    short: "Routing a small percentage of real traffic to a new model/prompt version before rolling it out fully, to catch regressions early with limited exposure.",
    long: "A canary differs from offline eval-based gating by exposing the new version to a slice of actual live traffic and real user behavior, which can surface issues an offline golden dataset didn't cover (distribution shift, edge cases the dataset didn't anticipate). It requires having real-time quality/cost/latency monitoring on the canary slice specifically, with a clear rollback trigger, or the canary provides a false sense of safety without actually being watched.",
    related: ["shadow-deployment", "regression-gating"],
    moduleId: "production",
  },
  {
    id: "shadow-deployment",
    term: "Shadow Deployment",
    short: "Running a new model/prompt version in parallel with production on real traffic, comparing its output, but never actually serving its result to users.",
    long: "Shadowing gives you real-traffic signal with zero user-facing risk (the shadow's output is logged and compared, never returned), which makes it strictly safer than canarying but also strictly more expensive (you're paying for both the production call and the shadow call on every request) and it can't observe how users would have reacted to the new version's output, since they never see it. It is best used as a pre-canary validation step, not a permanent substitute for canarying.",
    related: ["canary-deployment", "regression-gating"],
    moduleId: "production",
  },
  {
    id: "rate-limiting",
    term: "Rate Limiting",
    short: "Capping the number of requests a client (or the whole system) can make within a time window.",
    long: "Rate limiting protects against both abuse (a malicious or buggy client hammering an endpoint) and legitimate cost blowouts (an expensive LLM endpoint called far more than intended), and should be enforced server-side regardless of any client-side throttling, since client-side limits are trivially bypassable. Standard practice exposes the limit state to the client via headers (remaining quota, reset time) so well-behaved clients can self-throttle before hitting a hard 429, rather than discovering the limit only by failing.",
    related: ["quota", "circuit-breaker"],
    moduleId: "production",
  },
  {
    id: "quota",
    term: "Quota",
    short: "A cap on total usage (requests, tokens, or spend) over a longer period (daily/monthly), distinct from short-window rate limiting.",
    long: "Quotas address a different risk than rate limits: rate limiting prevents short-term bursts from overwhelming a system, while quotas prevent sustained, within-limit usage from running up an unexpectedly large bill or exhausting a provider-side allocation over days or weeks. Both are necessary in a cost-conscious LLM product — a client could stay comfortably under a per-minute rate limit while still burning through a monthly budget far faster than intended.",
    related: ["rate-limiting", "cost-per-token"],
    moduleId: "production",
  },
  {
    id: "cost-per-token",
    term: "Cost per Token",
    short: "The price a provider charges per unit of input or output tokens, usually different rates for input vs. output.",
    long: "Input and output tokens are typically priced differently (output is usually more expensive per token than input, reflecting generation compute cost), and prices vary by model tier and change over time — any specific number should be checked against current provider pricing pages rather than hardcoded or memorized, since this is exactly the kind of volatile fact that goes stale fastest. Cost estimation in an application should read from a maintained, swappable pricing table, not inline constants scattered through code.",
    related: ["model-routing", "quota"],
    moduleId: "production",
  },
  {
    id: "latency-budget",
    term: "Latency Budget",
    short: "The maximum acceptable end-to-end response time for a feature, allocated across its sub-steps (retrieval, generation, post-processing).",
    long: "Setting a latency budget forces explicit trade-off decisions before they become production incidents: if a RAG answer has a 3-second budget and retrieval alone takes 1.5 seconds, that leaves a hard constraint on how much generation time (and therefore which model, how much reasoning) is actually affordable. Budgets should be split per sub-stage (not just one end-to-end number) so you know exactly which stage to optimize when the budget is exceeded, rather than vaguely 'making it faster'.",
    related: ["time-to-first-token", "tokens-per-second"],
    moduleId: "production",
  },
  {
    id: "drift",
    term: "Drift (Model/Data Drift)",
    short: "A gradual change in a provider's model behavior over time, or in the distribution of real production inputs, that degrades previously-validated quality.",
    long: "Model drift happens even without any code change on your side — a provider silently updates a model version behind a stable endpoint name, or a 'latest' alias moves to a new checkpoint with subtly different behavior on your specific prompts. Data drift happens on the input side — real user queries evolve away from what your golden dataset represents. Both are reasons production eval monitoring (not just pre-deploy testing) matters: a system that passed every eval at launch can degrade silently months later for reasons entirely outside your own changes.",
    related: ["regression-gating", "golden-dataset", "observability"],
    moduleId: "production",
  },
  {
    id: "queueing",
    term: "Queueing / Backpressure",
    short: "Holding excess requests in a bounded queue (rather than processing everything immediately or rejecting outright) when concurrent capacity is exceeded.",
    long: "Queueing with a concurrency cap protects a downstream dependency (a rate-limited provider, a finite worker pool) from being overwhelmed by bursty demand, at the cost of added latency for queued requests — this is a deliberate trade-off, not a free improvement, and an unbounded queue just delays an overload problem rather than solving it (and can exhaust memory). A production-grade implementation bounds the queue depth itself and sheds load (fails fast) once even the queue is full, rather than queueing indefinitely.",
    related: ["rate-limiting", "circuit-breaker", "request-batching"],
    moduleId: "production",
  },
  {
    id: "truncate-oldest",
    term: "Truncate-Oldest (Context Strategy)",
    short: "A context-fitting strategy that drops the oldest messages first when a conversation exceeds the context window.",
    long: "Truncate-oldest is the simplest context-management strategy and preserves the most recent, usually most relevant, turns, but it can silently discard an early message that later turns still implicitly depend on (an instruction given once at the start of a long conversation, a fact established early on) with no signal to the model that anything is missing. It is a reasonable default for short-lived, recency-dominated conversations and a poor fit for long-running conversations with important early context.",
    related: ["context-window", "sliding-window", "truncate-middle"],
    moduleId: "fundamentals",
  },
  {
    id: "truncate-middle",
    term: "Truncate-Middle (Context Strategy)",
    short: "A context-fitting strategy that preserves the earliest and most recent messages, dropping from the middle of the conversation first.",
    long: "This strategy is motivated by the observation that the opening turns (initial instructions/context-setting) and the most recent turns (immediate relevant state) are often more valuable than middle turns, so it tries to keep both ends intact. It shares the 'lost in the middle' risk under a different name — if something genuinely important was established in the middle of a long conversation, truncate-middle will drop exactly that, so like all fixed heuristics it should be validated against your actual conversation patterns, not assumed universally correct.",
    related: ["context-window", "truncate-oldest", "sliding-window", "lost-in-the-middle"],
    moduleId: "fundamentals",
  },
  {
    id: "sliding-window",
    term: "Sliding Window (Context Strategy)",
    short: "A context-fitting strategy that keeps only the most recent N messages/tokens, continuously dropping older ones as the conversation grows.",
    long: "Sliding window is conceptually similar to truncate-oldest but framed as a continuously-maintained fixed-size window rather than a one-time cutoff reaction to overflow, which makes it a natural default for streaming/long-running chat sessions where you want a predictable, bounded context size on every single turn rather than an occasional large truncation event. The same limitation applies: anything outside the window is simply gone, with no summarization or preservation of its content.",
    related: ["context-window", "truncate-oldest", "truncate-middle"],
    moduleId: "fundamentals",
  },
  {
    id: "conversation-summarization",
    term: "Conversation Summarization (Context Strategy)",
    short: "A context-fitting strategy that compresses dropped/older messages into a shorter summary (via an LLM call) instead of discarding them outright.",
    long: "Summarization preserves the gist of older context at a fraction of the token cost, which is the most information-preserving of the context strategies, at the price of an extra LLM call (cost and latency) and the risk that the summary itself drops or distorts a detail that later turns actually needed. Because it depends on an LLM call, summarization also inherits that call's own failure modes (it is itself a `Run` worth tracking) — it is not a free, purely mechanical strategy like the other three.",
    related: ["context-window", "truncate-oldest", "sliding-window"],
    moduleId: "fundamentals",
  },
];
