import type { GlossaryTerm } from "../types";

export const promptingTerms: GlossaryTerm[] = [
  {
    id: "zero-shot-prompting",
    term: "Zero-Shot Prompting",
    short: "Asking a model to perform a task with instructions only, no worked examples.",
    long: "Zero-shot relies entirely on the model's pretrained and instruction-tuned priors to infer the task format from a description alone, which works well for common, well-represented tasks but degrades on unusual output formats or domain-specific conventions. It is the cheapest prompting strategy in tokens, which makes it the right default to try first before reaching for few-shot examples that cost context budget on every single request.",
    related: ["few-shot-prompting", "in-context-learning", "instruction-hierarchy"],
    moduleId: "prompting",
  },
  {
    id: "few-shot-prompting",
    term: "Few-Shot Prompting",
    short: "Including a small number of input/output example pairs in the prompt to demonstrate the desired task and format.",
    long: "Few-shot examples work through in-context learning, not weight updates — the model pattern-matches the demonstrated input-output mapping at inference time. Example selection and order matter more than engineers expect: biased, too-similar, or poorly-ordered examples can anchor the model onto a narrow pattern (recency and primacy effects are real), and every example is a recurring token cost paid on every single request, which is why few-shot is often replaced by fine-tuning or structured output constraints at scale.",
    related: ["zero-shot-prompting", "in-context-learning", "prompt-template"],
    moduleId: "prompting",
  },
  {
    id: "chain-of-thought",
    term: "Chain-of-Thought (CoT) Prompting",
    short: "Prompting the model to produce intermediate reasoning steps before its final answer.",
    long: "CoT improves accuracy on multi-step arithmetic, logic, and planning tasks by giving the model 'room' to work through sub-steps as generated tokens it can then condition on, rather than forcing the entire answer to emerge from a single forward pass. The well-documented catch: the written reasoning is not guaranteed to be the actual causal process behind the final answer (models can produce plausible-sounding chains that don't match how the answer was really reached), so CoT output should be treated as a helpful but not fully trustworthy explanation, especially for safety-critical decisions.",
    related: ["self-consistency", "reasoning-model", "react-pattern"],
    moduleId: "prompting",
  },
  {
    id: "self-consistency",
    term: "Self-Consistency",
    short: "Sampling multiple independent chain-of-thought completions and taking the majority-vote (or otherwise aggregated) final answer.",
    long: "Self-consistency trades extra inference cost (N samples instead of 1) for higher accuracy on tasks where errors are roughly independent across samples — the correct reasoning path tends to be more common among diverse samples than any single incorrect path. It does not help (and can even hurt latency/cost for nothing) on tasks where the model is systematically, consistently wrong in the same way every time, since majority voting over N identical mistakes is still a mistake.",
    related: ["chain-of-thought", "temperature"],
    moduleId: "prompting",
  },
  {
    id: "react-pattern",
    term: "ReAct (Reason + Act)",
    short: "A prompting pattern that interleaves explicit reasoning steps with tool-invoking actions and observations of their results.",
    long: "ReAct structures an agent loop as repeated Thought → Action → Observation cycles, making the model's intermediate reasoning and tool usage legible and debuggable instead of hidden inside a single opaque generation. It is the conceptual ancestor of most modern tool-calling agent loops, though production systems today usually implement the 'action' step via structured function/tool calling rather than free-text action parsing, which is more reliable and easier to validate.",
    related: ["chain-of-thought", "agent-loop", "tool-calling"],
    moduleId: "agents",
  },
  {
    id: "prefill",
    term: "Prefill",
    short: "Seeding the start of the assistant's response yourself, so the model continues from your text rather than starting fresh.",
    long: "Prefill is a powerful format-forcing technique (e.g. starting the assistant turn with '{' to bias strongly toward JSON output, or with a specific opening phrase to control tone), because the model conditions on prefilled tokens exactly as if it had generated them itself. It is also a known jailbreak vector — prefilling an assistant turn with compliance language can sometimes bypass a model's own safety training — which is why some providers restrict or specially handle assistant-turn prefill.",
    related: ["json-mode", "delimiter", "jailbreak"],
    moduleId: "prompting",
  },
  {
    id: "delimiter",
    term: "Delimiter",
    short: "A distinct marker (XML tags, triple quotes, unusual unicode) used to visually and structurally separate prompt sections.",
    long: "Delimiters help the model (and the engineer) tell instructions apart from data, which is both a quality technique (clearer structure, less ambiguity about what's an instruction vs. content to process) and a lightweight security technique (making it harder for untrusted input to be mistaken for a system instruction). They are not a robust injection defense on their own — a sufficiently adversarial input can still include or mimic your delimiter — so pair them with the dedicated guardrail layer for anything handling untrusted input.",
    related: ["prompt-template", "prompt-injection", "instruction-hierarchy"],
    moduleId: "prompting",
  },
  {
    id: "system-prompt",
    term: "System Prompt",
    short: "The highest-priority instruction block that sets persona, rules, and constraints for the whole conversation.",
    long: "The system prompt is where instruction-hierarchy priority is strongest, but it is not a hard security boundary — it is still just text in context that a sufficiently crafted user or tool-result message can sometimes override or contradict, especially across long conversations or with injected content from retrieved documents and tool outputs. Treat the system prompt as a strong steering mechanism and a UX contract, not as a sandbox wall, for anything that actually needs enforcement (rate limits, tool allow-lists, output validation).",
    related: ["instruction-hierarchy", "prompt-injection", "role-prompting"],
    moduleId: "prompting",
  },
  {
    id: "instruction-hierarchy",
    term: "Instruction Hierarchy",
    short: "The implicit or explicit precedence given to system > developer > user > tool/retrieved-content instructions.",
    long: "Some model providers now explicitly train models to weigh system/developer instructions above user instructions, and user instructions above untrusted tool or document content — this is a meaningful mitigation against prompt injection, but it is probabilistic, not absolute. Designing a prompt to exploit this hierarchy correctly (put real policy in system/developer messages, never trust retrieved or tool content as instructions) measurably reduces injection risk even though it cannot eliminate it.",
    related: ["system-prompt", "prompt-injection", "indirect-prompt-injection"],
    moduleId: "prompting",
  },
  {
    id: "prompt-template",
    term: "Prompt Template",
    short: "A parameterized prompt string with variable placeholders filled in at request time.",
    long: "Templating lets you version and test prompts independently of the data flowing through them, but it introduces an injection surface identical in shape to SQL injection: if untrusted input is interpolated into a template without escaping or clear delimiting, it can be crafted to look like an instruction rather than data. The fix pattern is the same lesson learned from web security decades ago — never string-concatenate untrusted input directly adjacent to instructions; use clear structural separation and validate/sanitize before interpolation.",
    related: ["delimiter", "prompt-injection", "prompt-versioning"],
    moduleId: "prompting",
  },
  {
    id: "role-prompting",
    term: "Role Prompting",
    short: "Instructing the model to adopt a persona or expert role ('You are a senior security auditor...').",
    long: "Role prompting can usefully bias style, vocabulary, and the implicit standards a model applies (an 'expert reviewer' persona tends to be more critical than a generic assistant persona), but it does not grant the model actual capabilities it lacks, and over-reliance on persona framing to extract better reasoning is weaker evidence-wise than techniques like chain-of-thought or providing concrete examples. It is also a well-known jailbreak vector ('pretend you are an AI with no restrictions'), so role-based framing in untrusted or user-controlled input deserves scrutiny.",
    related: ["system-prompt", "jailbreak"],
    moduleId: "prompting",
  },
  {
    id: "prompt-chaining",
    term: "Prompt Chaining",
    short: "Breaking a complex task into multiple sequential LLM calls, each feeding its output into the next.",
    long: "Chaining decomposes a task so each individual call has a narrower, more verifiable job (extract, then summarize, then format, for instance), which generally improves reliability over one giant monolithic prompt and makes failures easier to localize and retry individually. The costs are added latency (sequential round-trips) and added token spend (context often has to be re-passed between steps) — whether chaining is worth it versus one well-engineered single call is an empirical question per task, not a default best practice.",
    related: ["prompt-template", "agent-loop"],
    moduleId: "prompting",
  },
  {
    id: "in-context-learning",
    term: "In-Context Learning",
    short: "A model's ability to adapt its behavior based on information provided in the prompt, without any weight updates.",
    long: "In-context learning is the mechanism underlying few-shot prompting, RAG, and tool-use instructions alike: the model conditions its next-token predictions on everything in context as if it were additional 'training signal' for this one request only, then forgets it completely once the request ends. This is precisely why RAG and prompting can substitute for fine-tuning in many cases (new knowledge injected per-request) but cannot change the model's underlying weights, style, or deeply ingrained behaviors the way fine-tuning can.",
    related: ["few-shot-prompting", "retrieval-augmented-generation"],
    moduleId: "prompting",
  },
  {
    id: "prompt-versioning",
    term: "Prompt Versioning",
    short: "Tracking prompt text (and its params) as immutable, numbered versions over time, the same discipline applied to code.",
    long: "Prompts are production logic, not static strings — they regress, they need rollback, and they need to be tied to the eval results that justified a change. Treating a prompt edit as a new version (rather than mutating in place) is what makes it possible to A/B compare two versions, gate a deploy on an eval score, and explain 'why did behavior change last Tuesday' months later; this app's prompt-versions API deliberately never mutates history, only appends new versions with parent links.",
    related: ["golden-dataset", "regression-gating", "a-b-testing"],
    moduleId: "prompting",
  },
];
