import type { GlossaryTerm } from "../types";

export const ragChunkingTerms: GlossaryTerm[] = [
  {
    id: "chunking",
    term: "Chunking",
    short: "Splitting a document into smaller pieces before embedding and indexing, so retrieval can return relevant sub-sections.",
    long: "Chunk size is one of the highest-leverage, most under-tuned decisions in a RAG pipeline: too small and chunks lose surrounding context needed to answer correctly; too large and irrelevant text dilutes the embedding (and wastes context window when retrieved). There is no universally correct chunk size — it depends on document structure, query style, and the embedding model's own effective range, which is why a chunking lab that lets you compare chunk sizes side by side on the same corpus is genuinely useful, not just a parameter demo.",
    related: ["fixed-size-chunking", "semantic-chunking", "chunk-overlap", "recursive-chunking"],
    moduleId: "rag",
  },
  {
    id: "fixed-size-chunking",
    term: "Fixed-Size Chunking",
    short: "Splitting text into chunks of a constant token/character length, usually with some overlap.",
    long: "Fixed-size chunking is the simplest, cheapest-to-implement strategy and a reasonable baseline, but it is structure-blind — it will happily cut a sentence, a table row, or a code block in half purely because the character count hit the boundary, which can destroy the semantic coherence a chunk needs to be independently retrievable and useful. It remains a fine default for homogeneous, prose-heavy corpora where structural boundaries are less load-bearing.",
    related: ["chunking", "chunk-overlap", "recursive-chunking"],
    moduleId: "rag",
  },
  {
    id: "semantic-chunking",
    term: "Semantic Chunking",
    short: "Splitting text at points where meaning shifts (detected via embedding similarity between adjacent sentences) rather than at a fixed size.",
    long: "Semantic chunking computes embeddings for small units (sentences or paragraphs) and places chunk boundaries where similarity between consecutive units drops, aiming to keep each chunk topically coherent regardless of its raw length. It costs more at ingestion time (extra embedding calls just to decide where to cut) and can still misfire on ambiguous topic shifts, so it is best justified when retrieval quality on a real eval set actually improves over cheaper strategies — not adopted by default on the assumption that 'smarter' chunking is always better.",
    related: ["chunking", "fixed-size-chunking", "recursive-chunking"],
    moduleId: "rag",
  },
  {
    id: "recursive-chunking",
    term: "Recursive (Structure-Aware) Chunking",
    short: "Splitting hierarchically along document structure (sections, then paragraphs, then sentences) until chunks fit a target size.",
    long: "Recursive chunking tries a sequence of separators from coarsest to finest (e.g. markdown headers, then double newlines, then single newlines, then sentences) and only falls through to a finer separator when a piece is still too large, which tends to respect natural document boundaries far better than naive fixed-size splitting. It is the most common production default for structured text (markdown, HTML-derived, code documentation) because it is cheap (no extra embedding calls) yet structure-aware.",
    related: ["chunking", "fixed-size-chunking", "semantic-chunking"],
    moduleId: "rag",
  },
  {
    id: "chunk-overlap",
    term: "Chunk Overlap",
    short: "Repeating a small amount of text at the boundary between consecutive chunks so context isn't lost at a hard cut.",
    long: "Overlap mitigates the specific failure where an answer-relevant sentence gets split exactly at a chunk boundary and neither resulting chunk contains the complete thought; a typical overlap is a fraction (e.g. 10-20%) of the chunk size. Overlap is not free — it multiplies storage and embedding cost by however much duplication you introduce, and excessive overlap can cause the same information to be retrieved multiple times, crowding out other relevant chunks in a fixed top-k.",
    related: ["chunking", "fixed-size-chunking"],
    moduleId: "rag",
  },
  {
    id: "retrieval-augmented-generation",
    term: "Retrieval-Augmented Generation (RAG)",
    short: "Retrieving relevant external documents at query time and inserting them into the prompt so the model generates grounded on real content.",
    long: "RAG exists to solve two problems fine-tuning and prompting alone don't: giving a model access to knowledge it wasn't trained on (including private, changing, or very recent data) without retraining, and giving its answers citable grounding so claims can be checked against a source. RAG does not eliminate hallucination — it reduces it by giving the model relevant material to condition on, but the model can still ignore the retrieved content, misread it, or blend it with its own unsupported prior knowledge, which is why faithfulness evaluation against the retrieved context remains necessary even with RAG in place.",
    related: ["chunking", "hallucination", "grounding", "citation-grounding", "faithfulness"],
    moduleId: "rag",
  },
  {
    id: "hyde",
    term: "HyDE (Hypothetical Document Embeddings)",
    short: "Having the model first generate a hypothetical answer to the query, then embedding that answer (not the query) to retrieve.",
    long: "HyDE addresses the asymmetry between short, under-specified queries and the longer, differently-phrased documents that actually answer them: a hypothetical answer tends to be lexically and structurally closer to real documents than the bare query is, which can improve retrieval for queries that are terse, ambiguous, or phrased very differently from how the answer is written in the corpus. The cost is an extra LLM call per query before retrieval even starts, and if the hypothetical answer is confidently wrong, it can actively steer retrieval toward the wrong documents — a real failure mode worth testing for, not a theoretical one.",
    related: ["retrieval-augmented-generation", "query-rewriting", "multi-query-retrieval"],
    moduleId: "rag",
  },
  {
    id: "multi-query-retrieval",
    term: "Multi-Query Retrieval",
    short: "Generating several rephrased variants of the user's query and retrieving for each, then merging the results.",
    long: "Multi-query retrieval hedges against any single phrasing missing relevant documents due to vocabulary mismatch between the query and the corpus — different rephrasings act like different 'casts of the net'. It increases both LLM calls (to generate variants) and retrieval calls (one per variant) proportionally, and the merge/dedup step needs its own logic (often reciprocal rank fusion) to avoid simply flooding the context with near-duplicate chunks retrieved by multiple variants.",
    related: ["hyde", "query-rewriting", "reciprocal-rank-fusion", "retrieval-augmented-generation"],
    moduleId: "rag",
  },
  {
    id: "parent-document-retrieval",
    term: "Parent-Document Retrieval",
    short: "Indexing small chunks for precise retrieval matching, but returning each chunk's larger parent section/document for generation context.",
    long: "This pattern resolves a genuine tension in chunk sizing: small chunks embed and match more precisely (less topic dilution), but small chunks alone often lack enough surrounding context for the generator to produce a complete, well-grounded answer. By decoupling the retrieval unit (small chunk) from the context unit (its parent), you get precise matching and sufficient context simultaneously, at the cost of needing to store and look up the parent-child relationship, not just flat chunks.",
    related: ["chunking", "retrieval-augmented-generation", "contextual-compression"],
    moduleId: "rag",
  },
  {
    id: "contextual-compression",
    term: "Contextual Compression",
    short: "Post-retrieval filtering or summarizing of retrieved chunks to keep only the parts actually relevant to the query before generation.",
    long: "Compression targets the 'lost in the middle' and context-dilution problems directly: even correctly retrieved chunks often contain irrelevant surrounding text, and feeding all of it to the generator both wastes context budget and can distract the model from the actually-relevant sentence. The compression step itself is usually a cheap extraction or an LLM call, which adds latency and a new failure mode (the compressor discarding something that was actually needed) — it should be evaluated against end-to-end answer quality, not assumed to be strictly beneficial.",
    related: ["lost-in-the-middle", "retrieval-augmented-generation", "parent-document-retrieval"],
    moduleId: "rag",
  },
  {
    id: "agentic-rag",
    term: "Agentic RAG",
    short: "RAG where the model itself decides, iteratively, whether/what/how many times to retrieve, rather than following one fixed retrieve-then-generate pass.",
    long: "Agentic RAG turns retrieval into a tool the model can call repeatedly and adaptively — issuing a follow-up query if the first retrieval was insufficient, retrieving from different collections for different sub-questions, or deciding retrieval isn't needed at all for a given turn. This is strictly more flexible than single-pass RAG but also strictly more expensive and harder to debug (variable number of LLM and retrieval calls per request), and it inherits every general agent risk — looping, excessive tool calls, runaway cost — so it needs the same step/budget limits any agent loop needs.",
    related: ["retrieval-augmented-generation", "agent-loop", "multi-query-retrieval"],
    moduleId: "rag",
  },
  {
    id: "query-rewriting",
    term: "Query Rewriting",
    short: "Transforming the user's raw query into a better-suited retrieval query (e.g. resolving coreference, expanding abbreviations, standalone-izing a follow-up question).",
    long: "Conversational follow-up questions ('what about the second one?') are often terrible standalone retrieval queries because they depend on prior turns for meaning; query rewriting uses the conversation history to produce a self-contained query before it ever reaches the retriever. Done poorly (e.g. rewriting introduces the model's own assumptions about what 'the second one' means), it can actively corrupt retrieval, so it is worth testing explicitly against multi-turn conversational eval cases, not just single-turn queries.",
    related: ["hyde", "multi-query-retrieval", "retrieval-augmented-generation"],
    moduleId: "rag",
  },
  {
    id: "lost-in-the-middle",
    term: "Lost-in-the-Middle",
    short: "The observed tendency of LLMs to pay less attention to information placed in the middle of a long context than at the start or end.",
    long: "This is an empirical finding about long-context attention patterns, not a universal law that holds identically across every model and context length — but it is common enough that 'the answer is in there somewhere in a 50-chunk context, but the model missed it' is frequently explained by where in the context the relevant chunk landed, not just whether it was retrieved at all. Practical mitigations include keeping top-k smaller and more precise (better reranking), and in some pipelines deliberately placing the highest-confidence chunk near the start or end of the context.",
    related: ["context-precision", "reranking", "retrieval-augmented-generation"],
    moduleId: "rag",
  },
  {
    id: "citation-grounding",
    term: "Citation / Source Grounding",
    short: "Tying each claim in a generated answer back to the specific retrieved chunk(s) that support it.",
    long: "Citations turn an opaque generated answer into something a human can actually verify, by exposing which chunk/document each statement is attributed to — this is what lets a user (or an automated faithfulness checker) catch the model asserting something the retrieved context never actually said. Reliable citation requires either structured generation (the model outputs claim-to-chunk-id mappings explicitly) or a separate verification pass; simply trusting a model's free-text citations without checking them against the actual chunk content reintroduces the hallucination risk citations were meant to catch.",
    related: ["retrieval-augmented-generation", "faithfulness", "hallucination"],
    moduleId: "rag",
  },
  {
    id: "hallucination",
    term: "Hallucination",
    short: "A model generating content that is fluent and confident but factually wrong or unsupported by any real source.",
    long: "Hallucination is a structural property of how LLMs generate text — predicting the most plausible next token, not querying a verified knowledge base — not a rare bug to be patched away; it occurs most often on long-tail facts, numbers, citations, and anything outside the training distribution's dense coverage. RAG, grounding, and citation-checking reduce hallucination's practical impact by giving the model (and your verification layer) something concrete to condition on and check against, but no current technique eliminates it entirely, which is why high-stakes outputs still need a verification or human-review layer.",
    related: ["grounding", "retrieval-augmented-generation", "faithfulness"],
    moduleId: "rag",
  },
  {
    id: "grounding",
    term: "Grounding",
    short: "Anchoring a model's output to verifiable external evidence (retrieved documents, tool results, structured data) rather than its unaided prior knowledge.",
    long: "A grounded answer is one where the claims can be traced to something outside the model's parametric memory — a retrieved chunk, a tool call's return value, a database row — which is what makes faithfulness and citation checking possible in the first place. Grounding reduces but does not guarantee correctness: the model can still misread or misquote grounded evidence, which is a distinct failure mode from hallucinating with no evidence at all, and the two should be measured separately in an eval suite.",
    related: ["hallucination", "faithfulness", "retrieval-augmented-generation"],
    moduleId: "rag",
  },
];
