import type { GlossaryTerm } from "../types";

export const samplingDecodingTerms: GlossaryTerm[] = [
  {
    id: "temperature",
    term: "Temperature",
    short: "A scalar that rescales logits before softmax, controlling how sharply the model prefers the highest-probability token.",
    long: "Low temperature (approaching 0) sharpens the distribution toward the argmax token, producing near-deterministic, conservative output; high temperature flattens it, increasing diversity but also the chance of incoherent or off-task completions. Temperature does not add randomness by itself — it reshapes the probability distribution that top-k/top-p/sampling then draws from — so temperature=0 with a fixed seed should be close to deterministic, while temperature=0 without a fixed seed can still vary slightly on hosted providers due to batching/kernel non-determinism.",
    related: ["logit", "top-p", "top-k", "seed", "determinism", "nucleus-sampling"],
    moduleId: "fundamentals",
  },
  {
    id: "top-p",
    term: "Top-p (Nucleus Sampling)",
    short: "Sample only from the smallest set of tokens whose cumulative probability reaches p.",
    long: "Top-p dynamically truncates the candidate set based on the actual shape of the distribution: in a confident distribution the nucleus might contain only 2-3 tokens, while in an uncertain one it might include dozens. This adapts better than a fixed top-k across very different prompts, but combining a low top-p with a high temperature can still produce a wide, low-quality nucleus — the parameters interact, they are not independent dials.",
    related: ["top-k", "temperature", "nucleus-sampling", "logit"],
    moduleId: "fundamentals",
  },
  {
    id: "top-k",
    term: "Top-k",
    short: "Restrict sampling to the k highest-probability tokens at each step, discarding the rest before sampling.",
    long: "Top-k is a fixed-size truncation (always exactly k candidates considered, regardless of how confident the distribution is), which makes it simpler but less adaptive than top-p: a very confident distribution wastes probability mass on k-1 tokens that should have near-zero chance, while a very uncertain distribution is artificially narrowed to k options that may all be poor. Many providers let you combine top-k and top-p; when both are set, the intersection (or a provider-specific order of application) applies, and that order is not standardized across providers — check provider docs.",
    related: ["top-p", "temperature", "logprobs"],
    moduleId: "fundamentals",
  },
  {
    id: "nucleus-sampling",
    term: "Nucleus Sampling",
    short: "The sampling strategy that top-p implements: draw from the smallest probability-mass 'nucleus' that covers p.",
    long: "Nucleus sampling was introduced specifically to fix a failure mode of plain top-k and pure temperature sampling: both can either waste mass on implausible tokens (too large a fixed k) or over-truncate a genuinely uncertain distribution (too small a fixed k). By sizing the candidate set to the actual shape of the distribution at each step, it tends to avoid both degenerate repetition (too greedy) and incoherent rambling (too random) better than either alone, though it still requires tuning per use case.",
    related: ["top-p", "top-k", "temperature"],
    moduleId: "fundamentals",
  },
  {
    id: "greedy-decoding",
    term: "Greedy Decoding",
    short: "Always picking the single highest-probability token at every step.",
    long: "Greedy decoding is deterministic given identical logits, which makes it attractive for reproducibility, but it is myopic: the locally-best token at step N can lead to a globally worse sequence than a token that looked slightly less likely at step N but opened up a much better continuation. This is the core motivation for beam search and for sampling-based exploration (self-consistency, best-of-n) in tasks like multi-step reasoning where the best next token is not always the best overall path.",
    related: ["beam-search", "logit", "self-consistency", "determinism"],
    moduleId: "fundamentals",
  },
  {
    id: "beam-search",
    term: "Beam Search",
    short: "Keeping the top-b partial sequences at each decoding step instead of just one, to search for a higher-probability full sequence.",
    long: "Beam search trades compute (b parallel continuations) for a better approximation of the overall highest-probability sequence than greedy decoding gives, which is why it is common in constrained-output tasks like translation. It is rarely used for open-ended chat/instruction-following generation in modern LLM APIs because it tends to produce bland, generic, repetitive text when optimizing purely for sequence probability — most provider chat completion endpoints expose sampling parameters, not a beam-width parameter.",
    related: ["greedy-decoding", "logit"],
    moduleId: "fundamentals",
  },
  {
    id: "logprobs",
    term: "Log Probabilities (logprobs)",
    short: "The log-probability a model assigned to the token it actually emitted (and optionally to top alternative tokens at that step).",
    long: "Logprobs let you inspect model confidence token-by-token without needing access to internal weights, which is the basis for confidence-based routing, hallucination heuristics (low-confidence spans), and 'why did it pick this word' explanations. Not all providers expose logprobs on all endpoints/models, and the semantics (e.g. whether they reflect pre- or post-penalty adjustment) vary — verify against the specific provider's docs before building a feature that depends on exact values.",
    related: ["logit", "temperature", "top-k"],
    moduleId: "fundamentals",
  },
  {
    id: "stop-sequence",
    term: "Stop Sequence",
    short: "A string that, once generated, tells the model/API to end the completion immediately.",
    long: "Stop sequences are the simplest and cheapest way to bound output (cheaper than max-token truncation because you don't pay for or wait on unwanted trailing tokens), commonly used to end a turn at a role delimiter or a structured-output terminator. A subtle gotcha: if the stop sequence can also appear legitimately inside desired output (e.g. the delimiter string appearing in a code sample), the completion will be cut short there too — design delimiters to be unlikely to occur in valid content.",
    related: ["finish-reason", "delimiter"],
    moduleId: "fundamentals",
  },
  {
    id: "frequency-penalty",
    term: "Frequency Penalty",
    short: "Reduces the logit of a token proportionally to how many times it has already appeared in the output so far.",
    long: "Frequency penalty directly fights repetitive output by making already-used tokens progressively less attractive the more they recur, which is useful against degenerate loops but can also push a model away from legitimately necessary repeated terms (names, keywords, code identifiers) if set too high. It composes with presence penalty and temperature; tuning it in isolation without testing against your actual task's vocabulary is a common way to get subtly worse output.",
    related: ["presence-penalty", "repetition-penalty", "temperature"],
    moduleId: "fundamentals",
  },
  {
    id: "presence-penalty",
    term: "Presence Penalty",
    short: "Reduces the logit of a token by a flat amount if it has appeared at all, regardless of how many times.",
    long: "Unlike frequency penalty (which scales with repeat count), presence penalty applies the same fixed discouragement the moment a token has occurred once — it nudges the model toward introducing new topics/vocabulary rather than specifically suppressing loops. The two are often confused because both fight repetition, but they shape output differently enough that swapping one for the other can change results in ways worth testing empirically rather than assuming interchangeability.",
    related: ["frequency-penalty", "repetition-penalty"],
    moduleId: "fundamentals",
  },
  {
    id: "repetition-penalty",
    term: "Repetition Penalty",
    short: "A multiplicative penalty (common in open-source/local inference stacks) applied to logits of tokens already seen in context.",
    long: "Repetition penalty is the open-source-ecosystem (e.g. llama.cpp/Ollama-style) analogue to the frequency/presence penalties exposed by hosted chat APIs, and the exact formula and default value differ by inference stack — a repetition penalty of 1.1 on one runtime is not guaranteed to behave like 1.1 on another. When migrating a prompt/param set between a hosted provider and a local model, re-tune these penalties rather than copying values across ecosystems.",
    related: ["frequency-penalty", "presence-penalty"],
    moduleId: "fundamentals",
  },
  {
    id: "seed",
    term: "Seed",
    short: "A fixed value for the random number generator used in sampling, intended to make generations reproducible.",
    long: "Setting a seed should make sampling deterministic for identical (model, messages, params) — this is explicitly required of the MockProvider so demos are reproducible with zero keys — but on hosted providers, 'best-effort' determinism is common wording: differences in batching, hardware, or backend routing can still produce different outputs for the same seed across requests or over time. Never build a correctness-critical feature (e.g. a test assertion) on the assumption that a seeded hosted-provider call is bit-for-bit reproducible; verify, and prefer the mock/local path for anything that truly requires determinism.",
    related: ["determinism", "temperature"],
    moduleId: "fundamentals",
  },
  {
    id: "determinism",
    term: "Determinism",
    short: "Whether identical inputs reliably produce identical outputs.",
    long: "True determinism in LLM inference requires fixed weights, fixed numerical precision, fixed batching/scheduling, and a fixed seed — hosted multi-tenant providers typically cannot guarantee all of these simultaneously, so 'deterministic' there usually means 'low variance, not guaranteed-identical'. For anything that needs to be exactly reproducible (grading, regression tests, teaching demos), use temperature=0 plus a seed on a provider that documents strict determinism, or fall back to a local/mock model you control end to end.",
    related: ["seed", "temperature", "greedy-decoding"],
    moduleId: "fundamentals",
  },
  {
    id: "streaming",
    term: "Streaming",
    short: "Sending generated tokens to the client incrementally as they are produced, rather than waiting for the full completion.",
    long: "Streaming improves perceived latency (the user sees the first words quickly) even though total generation time is roughly unchanged, and it is the only practical way to show progress on long completions. It adds real engineering complexity: partial-JSON parsing for structured output, reconnection/resume semantics (or the deliberate lack thereof), and the need to still persist a complete, well-formed record of the run once the stream ends or errors mid-way.",
    related: ["time-to-first-token", "tokens-per-second"],
    moduleId: "fundamentals",
  },
  {
    id: "time-to-first-token",
    term: "Time to First Token (TTFT)",
    short: "Latency from request sent to the first output token received.",
    long: "TTFT is dominated by the prefill phase — processing the entire input prompt through the model once to populate the KV cache — so TTFT scales with input length far more than with expected output length. This is why a huge system prompt or a large RAG context can make a request feel slow to start even if the final answer is short, and why prompt caching (reusing a previously-computed prefix's KV state) specifically targets TTFT.",
    related: ["kv-cache", "streaming", "tokens-per-second"],
    moduleId: "fundamentals",
  },
  {
    id: "tokens-per-second",
    term: "Tokens per Second (Decode Throughput)",
    short: "The rate at which output tokens are generated after the first token, during the sequential decode phase.",
    long: "Decode throughput is governed by the sequential, one-token-at-a-time nature of autoregressive generation plus hardware/batching factors, and it is largely independent of prompt length (unlike TTFT). A request with a short prompt but a long requested output will have fast TTFT but still take a while overall if tokens/sec is low — the two metrics answer different questions and both should be reported separately in a latency lab, never collapsed into one 'response time' number.",
    related: ["time-to-first-token", "autoregressive-decoding", "streaming"],
    moduleId: "fundamentals",
  },
  {
    id: "finish-reason",
    term: "Finish Reason",
    short: "The provider-reported cause a generation stopped: natural end, stop sequence, max tokens, tool call, content filter, or error.",
    long: "Finish reason is the first thing to check when output looks truncated or malformed — a response cut off by a max-tokens limit looks very different from one that genuinely finished, and a structured-output parse failure caused by truncation has a completely different fix (raise max_tokens) than one caused by the model emitting malformed JSON. Provider-specific finish reason strings are not standardized across Anthropic/OpenAI/Ollama, so any abstraction layer over multiple providers needs to normalize them.",
    related: ["stop-sequence", "json-mode"],
    moduleId: "fundamentals",
  },
  {
    id: "thinking-budget",
    term: "Thinking Budget",
    short: "A tunable allowance of extra internal reasoning tokens a 'reasoning model' is allowed to spend before producing its final answer.",
    long: "Reasoning models can allocate a variable amount of hidden or visible intermediate computation per request; a thinking budget caps that allowance, trading latency/cost for (usually) better performance on multi-step problems, with diminishing and sometimes negative returns past a task-dependent point. Treat specific budget sizes and their exact effect on a given model as volatile and provider-specific — tune it empirically per task rather than copying a number from a blog post.",
    related: ["reasoning-model", "chain-of-thought"],
    moduleId: "advanced",
  },
  {
    id: "reasoning-model",
    term: "Reasoning Model",
    short: "A model variant trained/tuned to perform extended internal deliberation before answering, often exposing a thinking-budget control.",
    long: "Reasoning models tend to outperform equivalent non-reasoning models on multi-step math, coding, and planning tasks precisely because they spend more compute per answer, but that compute costs real latency and money — they are not a strict upgrade for simple, latency-sensitive, or high-volume tasks. Whether 'thinking' tokens are billed, visible, or redacted differs by provider and is worth checking before estimating cost.",
    related: ["thinking-budget", "chain-of-thought"],
    moduleId: "advanced",
  },
  {
    id: "multimodal-model",
    term: "Multimodal Model",
    short: "A model that accepts (and sometimes generates) more than one modality — text plus images, audio, or video.",
    long: "Multimodal input is typically handled by encoding non-text modalities (e.g. image patches) into the same embedding space the text transformer operates on, so the model can attend across modalities jointly rather than processing them separately. Not every model in a family supports every modality, and capability (e.g. OCR-quality text-in-image reading, video frame sampling rate) varies widely — check a specific model's documented capabilities (`ModelInfo.supportsVision` in this app) before assuming image support.",
    related: ["vision-language-model"],
    moduleId: "advanced",
  },
  {
    id: "vision-language-model",
    term: "Vision-Language Model (VLM)",
    short: "A multimodal model specifically combining an image encoder with a language model for joint image+text understanding.",
    long: "A VLM typically patches an image, encodes patches with a vision encoder (often a pretrained CNN or vision transformer), projects those patch embeddings into the language model's embedding space, and lets self-attention mix image and text tokens together. Image tokenization cost is non-trivial — a single high-resolution image can consume hundreds to thousands of tokens of context depending on the provider's encoding scheme, which materially affects both context-budget and cost math for image-heavy workloads.",
    related: ["multimodal-model", "context-window"],
    moduleId: "advanced",
  },
];
