import type { GlossaryTerm } from "../types";

export const securityTerms: GlossaryTerm[] = [
  {
    id: "prompt-injection",
    term: "Prompt Injection",
    short: "Crafting input so the model follows attacker-supplied instructions instead of (or in addition to) the application's intended instructions.",
    long: "Prompt injection is the LLM-era analogue of SQL/command injection: it exploits the fact that instructions and data share the same channel (plain text in the prompt), so there is no hard syntactic boundary preventing attacker-controlled text from being interpreted as a command. Full prevention is an open problem — defense is layered (instruction hierarchy, input/output filtering, least-privilege tool access, output validation) rather than solved by any single technique, which is why OWASP ranks it as the top LLM application risk.",
    related: ["direct-prompt-injection", "indirect-prompt-injection", "jailbreak", "owasp-llm-top-10"],
    moduleId: "security",
  },
  {
    id: "direct-prompt-injection",
    term: "Direct Prompt Injection",
    short: "An attacker directly supplies malicious instructions through a normal user-input channel (chat message, form field).",
    long: "Direct injection is the easier case to defend against relative to indirect injection, because the attacker's text is at least recognizable as 'user input' structurally — the mitigation surface includes input delimiting, instruction-hierarchy-aware system prompts, and output validation. It is still effective against naively built applications that simply concatenate user text into a prompt without any structural separation from system instructions.",
    related: ["prompt-injection", "indirect-prompt-injection", "jailbreak"],
    moduleId: "security",
  },
  {
    id: "indirect-prompt-injection",
    term: "Indirect Prompt Injection",
    short: "Malicious instructions hidden inside content the model retrieves or is given to process — a document, a web page, a tool result — not typed by the user.",
    long: "Indirect injection is more dangerous in practice than direct injection precisely because the victim (the user asking a question) never typed the malicious text themselves — it arrives via a RAG document, a scraped webpage, an email the agent is summarizing, or a tool's return value, all of which the application implicitly trusts as 'content to process' rather than 'instructions to follow'. This is the primary risk model for RAG and agent systems with any external data access, and it is why untrusted retrieved/tool content must never be treated with the same instruction-following weight as the system/developer prompt.",
    related: ["prompt-injection", "direct-prompt-injection", "instruction-hierarchy", "tool-abuse"],
    moduleId: "security",
  },
  {
    id: "jailbreak",
    term: "Jailbreak",
    short: "A prompt crafted specifically to bypass a model's safety training and get it to produce content/actions it was tuned to refuse.",
    long: "Jailbreaks exploit the gap between a model's safety training distribution and the space of possible inputs — role-play framing, hypothetical/fictional framing, encoding tricks, and multi-turn erosion ('just answer part of it, now a bit more...') are all common families. Jailbreak resistance is a continuously moving target (provider safety training improves, new jailbreak techniques emerge), so any system with real stakes needs defense layers beyond relying on the base model's safety training alone — output filtering, policy classifiers, and human review for high-risk categories.",
    related: ["prompt-injection", "role-prompting", "red-teaming"],
    moduleId: "security",
  },
  {
    id: "data-exfiltration",
    term: "Data Exfiltration (LLM context)",
    short: "Getting a model or agent to leak sensitive data (system prompt contents, other users' data, API keys, tool outputs) to an unauthorized party.",
    long: "Exfiltration attacks often combine prompt injection with a covert channel — e.g. instructing the model to encode sensitive text into a URL parameter of an image it's asked to render, or into a tool call argument that is logged/transmitted somewhere the attacker controls. Defenses include never putting secrets in a place the model can read and repeat (keep API keys server-side, never in the prompt), restricting what tools can transmit data externally, and allow-listing any outbound network/fetch capability so the agent cannot be tricked into sending data to an arbitrary attacker-controlled endpoint.",
    related: ["prompt-leaking", "least-privilege", "sandboxing", "tool-abuse"],
    moduleId: "security",
  },
  {
    id: "pii-redaction",
    term: "PII Redaction",
    short: "Detecting and removing/masking personally identifiable information before it is logged, stored, or sent to a third-party model provider.",
    long: "PII redaction has to happen at the right layer and the right time — redacting before logging prevents PII from leaking into log aggregation systems and their broader access lists, while redacting before sending to an external model provider reduces exposure if that provider's data-handling terms are a concern. Naive regex-based redaction (common for emails, phone numbers, SSNs) misses context-dependent PII (a name in a sentence, a rare combination of non-obviously-identifying details), so high-stakes redaction pipelines combine pattern matching with a model-based or rule-based entity classifier and treat it as probabilistic risk reduction, not a guarantee.",
    related: ["content-moderation", "guardrail"],
    moduleId: "security",
  },
  {
    id: "content-moderation",
    term: "Content Moderation",
    short: "Classifying model input and/or output against policy categories (violence, self-harm, hate, sexual content, etc.) and blocking/flagging violations.",
    long: "Moderation can run on input (block a request before it ever reaches the model), on output (check what the model produced before showing it to the user), or both — input moderation is cheaper and catches bad requests early, but output moderation catches the case where a seemingly benign request still produces problematic content. Treat moderation classifiers like any other ML model: they have false positives (legitimate content blocked) and false negatives (violating content missed), and the acceptable trade-off point is a product decision, not purely a technical one.",
    related: ["pii-redaction", "guardrail", "jailbreak"],
    moduleId: "security",
  },
  {
    id: "least-privilege",
    term: "Least Privilege (LLM/agent context)",
    short: "Granting a model or agent only the exact tools, data access, and permissions needed for its specific task — nothing broader.",
    long: "Least privilege is the single most effective structural defense against both prompt injection and plain model mistakes, because it bounds the blast radius of any single bad decision regardless of why the model made it (tricked by an attacker, or just wrong). In practice this means per-task tool allow-lists (not 'give the agent every tool, just in case'), scoped API credentials rather than admin keys, and sandboxed execution for anything that touches the filesystem or network.",
    related: ["allow-list", "sandboxing", "tool-registry", "human-in-the-loop"],
    moduleId: "security",
  },
  {
    id: "sandboxing",
    term: "Sandboxing",
    short: "Running untrusted or risky operations (code execution, file access) in an isolated environment with no access to the host filesystem or network.",
    long: "Sandboxing is what makes giving an LLM agent a code-execution tool defensible at all — without isolation, a model-generated script (whether buggy, misguided, or maliciously injected) could read/write arbitrary host files or make arbitrary network calls. A correct sandbox denies by default (no host FS, no network) and only exposes exactly the resources a specific tool legitimately needs, implemented via a real isolation boundary (container, VM, restricted worker) rather than a soft convention the model is merely asked to respect.",
    related: ["least-privilege", "allow-list", "tool-abuse"],
    moduleId: "security",
  },
  {
    id: "owasp-llm-top-10",
    term: "OWASP Top 10 for LLM Applications",
    short: "A community-maintained ranked list of the most critical security risks specific to LLM-powered applications.",
    long: "The list (covering risks like prompt injection, insecure output handling, training data poisoning, model denial of service, and excessive agency, among others) gives engineers a shared vocabulary and checklist for LLM-specific threat modeling, analogous to the original OWASP Top 10 for web applications. Specific risk rankings and item wording are revised periodically by OWASP — check the current published list rather than relying on a memorized version when doing a real security review.",
    related: ["prompt-injection", "data-exfiltration", "guardrail"],
    moduleId: "security",
  },
  {
    id: "prompt-leaking",
    term: "Prompt Leaking",
    short: "Tricking a model into revealing its own system prompt or other instructions that were meant to stay hidden from the user.",
    long: "Prompt leaking is a specific, narrow form of data exfiltration where the target is the application's own configuration (system prompt, few-shot examples, internal tool definitions) rather than user data — valuable to an attacker because it reveals how to craft more effective injections or simply exposes proprietary prompt engineering. Treating the system prompt as 'secret' is a weak defense on its own (models can often be induced to repeat context verbatim); if the system prompt's exposure would be genuinely damaging, that is a sign sensitive logic belongs in code-level enforcement, not prompt text.",
    related: ["data-exfiltration", "system-prompt", "prompt-injection"],
    moduleId: "security",
  },
  {
    id: "tool-abuse",
    term: "Tool Abuse",
    short: "An attacker (via prompt injection) manipulating an agent into calling a legitimate tool in a way that causes harm.",
    long: "Tool abuse doesn't require the attacker to introduce a new capability — it hijacks a tool the application legitimately provides (e.g. a send-email tool, a delete-file tool, a payment tool) and tricks the agent into invoking it for the attacker's benefit instead of the user's. This is exactly why tool registries mark dangerous tools explicitly and gate them behind human-in-the-loop approval or strict argument validation — the defense has to assume the model's decision to call a tool can be manipulated, not just that the tool itself is safe in isolation.",
    related: ["indirect-prompt-injection", "least-privilege", "human-in-the-loop", "tool-registry"],
    moduleId: "security",
  },
  {
    id: "guardrail",
    term: "Guardrail",
    short: "Any mechanism — rule-based, classifier-based, or structural — that constrains model/agent behavior to stay within acceptable bounds.",
    long: "'Guardrail' is an umbrella term spanning very different mechanisms with different guarantees: a regex-based input filter, an ML moderation classifier, a tool allow-list, output schema validation, and human-in-the-loop approval are all guardrails, but they catch different failure classes and none is individually sufficient. A mature guardrail system is layered (defense in depth) specifically because any single layer can be bypassed, and the goal is to make the combined probability of a harmful outcome acceptably low, not to claim any one layer is unbreakable.",
    related: ["defense-in-depth", "content-moderation", "pii-redaction", "least-privilege"],
    moduleId: "security",
  },
  {
    id: "red-teaming",
    term: "Red-Teaming",
    short: "Deliberately and systematically attacking a system (with injections, jailbreaks, edge cases) to find its security/safety weaknesses before real adversaries do.",
    long: "Red-teaming an LLM application should be structured and repeatable, not ad hoc — a catalog of known attack categories (direct/indirect injection, jailbreak, exfiltration, tool abuse) run against the system with and without each guardrail layer enabled gives a measurable before/after picture of what each layer actually buys you. This app's deliberately vulnerable demo bot exists specifically to let you run real attacks safely (mock tools only, no real side effects) and see guardrails catch them, which is the same practice-safely-first principle real red-teaming programs follow with isolated staging environments.",
    related: ["jailbreak", "prompt-injection", "guardrail", "owasp-llm-top-10"],
    moduleId: "security",
  },
  {
    id: "allow-list",
    term: "Allow-List",
    short: "An explicit list of permitted values (tools, domains, actions) where anything not listed is denied by default.",
    long: "Allow-lists are the 'deny by default' counterpart to least privilege: rather than trying to enumerate and block every bad tool, domain, or action (a deny-list, which is always incomplete against a creative attacker), you enumerate the specific things known to be safe and needed, and reject everything else automatically. This app's HTTP fetch tool and per-run tool registry both use allow-lists for exactly this reason — it is far easier to reason about 'can this agent reach example-internal-api.com' when the answer comes from a short explicit list than from an attempt to block every malicious domain in existence.",
    related: ["least-privilege", "sandboxing", "tool-registry"],
    moduleId: "security",
  },
  {
    id: "defense-in-depth",
    term: "Defense in Depth",
    short: "Layering multiple independent security controls so that no single control's failure compromises the whole system.",
    long: "Applied to LLM security, this means never relying on exactly one mitigation — e.g. instruction-hierarchy training alone, or output moderation alone — because each individual layer has documented bypasses; the combination of instruction hierarchy, least-privilege tool access, input/output filtering, and human review for high-risk actions is what makes a system resilient to any one layer failing. The practical test of defense in depth is asking, for each guardrail, 'if this specific layer were absent or bypassed, what is the next layer that would still catch the problem?'",
    related: ["guardrail", "least-privilege", "prompt-injection"],
    moduleId: "security",
  },
];
