import type { GlossaryTerm } from "../types";

export const tokenizationContextTerms: GlossaryTerm[] = [
  {
    id: "token",
    term: "Token",
    short: "The smallest unit of text an LLM reads or writes — roughly 3/4 of a word in English.",
    long: "A token is a chunk of text (a word, sub-word, punctuation mark, or byte sequence) produced by a tokenizer and mapped to an integer id that the model actually operates on. Models never see raw characters — they see token ids, embedded into vectors. Token boundaries rarely match human intuition about words, which is why counting 'characters' or 'words' to estimate cost or context usage is unreliable; always count tokens with the model's own tokenizer.",
    related: ["tokenization", "bpe", "context-window", "vocabulary-size"],
    moduleId: "fundamentals",
  },
  {
    id: "tokenization",
    term: "Tokenization",
    short: "The algorithm that splits raw text into tokens before it reaches the model.",
    long: "Tokenization is a deterministic, model-specific preprocessing step — different model families (and even different versions of the same family) can tokenize identical text differently, producing different counts and different costs. Senior engineers tokenize client-side with the correct tokenizer (or a verified approximation) before trusting any token-budget math, because an off-by-one tokenizer mismatch compounds across long conversations and silently truncates context.",
    related: ["token", "bpe", "context-window"],
    moduleId: "fundamentals",
  },
  {
    id: "bpe",
    term: "Byte-Pair Encoding (BPE)",
    short: "A sub-word tokenization algorithm that iteratively merges the most frequent adjacent byte/character pairs.",
    long: "BPE builds a vocabulary by starting from individual bytes or characters and greedily merging the most frequent adjacent pair until a target vocabulary size is reached. It balances vocabulary size against sequence length: common words become single tokens while rare words are split into sub-word pieces, so the model never hits a true out-of-vocabulary wall. Byte-level BPE (used by GPT-style tokenizers) operates on raw UTF-8 bytes, which is why it handles arbitrary Unicode and code without special-casing, at the cost of sometimes splitting non-English text into noticeably more tokens than English.",
    related: ["tokenization", "token", "vocabulary-size"],
    moduleId: "fundamentals",
  },
  {
    id: "vocabulary-size",
    term: "Vocabulary Size",
    short: "The number of distinct token ids a tokenizer can produce.",
    long: "Vocabulary size is a tuning knob fixed at pretraining time: larger vocabularies shorten sequences (fewer tokens per sentence, cheaper attention) but enlarge the embedding and output-projection matrices and can hurt rare-token quality. It differs across model families and is one reason the same text costs different token counts on different providers — never assume a universal 'tokens per word' ratio across models.",
    related: ["tokenization", "bpe", "token"],
    moduleId: "fundamentals",
  },
  {
    id: "context-window",
    term: "Context Window",
    short: "The maximum number of tokens (input + output) a model can attend to in one request.",
    long: "The context window bounds everything: system prompt, conversation history, retrieved documents, tool definitions, and the generated output all share this single budget. Exceeding it causes either a hard error or silent truncation depending on the client, and because attention cost scales roughly quadratically with sequence length (before optimizations like KV caching and sparse/sliding-window attention), using the full window is also a latency and cost decision, not just a correctness one. Treat the window size as 'check provider docs for current values' — it changes across model versions and is easy to misstate from memory.",
    related: ["token", "kv-cache", "truncate-oldest", "sliding-window"],
    moduleId: "fundamentals",
  },
  {
    id: "kv-cache",
    term: "KV Cache",
    short: "Cached key/value attention tensors from previous tokens so autoregressive decoding doesn't recompute them.",
    long: "During autoregressive generation, each new token's attention needs the key and value projections of every prior token; recomputing them from scratch at every step would make generation quadratically expensive. The KV cache stores those projections once and reuses them, which is why time-to-first-token and per-token latency behave so differently (prefill fills the cache for the whole prompt at once; decode appends one token at a time). KV cache memory grows linearly with context length and batch size and is frequently the real bottleneck behind 'why is my long-context request slow and memory-hungry' — not raw FLOPs.",
    related: ["attention", "context-window", "time-to-first-token", "autoregressive-decoding"],
    moduleId: "fundamentals",
  },
  {
    id: "attention",
    term: "Attention",
    short: "The mechanism by which a transformer weighs how much each token should influence the representation of every other token.",
    long: "Attention computes a weighted sum over all tokens' value vectors, where weights come from the similarity (dot product) between a query vector and each token's key vector. This lets the model dynamically decide which prior tokens matter for predicting the next one, as opposed to a fixed-window convolution or recurrence. The 'attention heatmap' visualizations popular in explainer tools are illustrative at best for hosted models — most provider APIs do not expose real attention weights, so any such visualization should be clearly labeled as an approximation.",
    related: ["self-attention", "multi-head-attention", "transformer", "causal-masking"],
    moduleId: "fundamentals",
  },
  {
    id: "self-attention",
    term: "Self-Attention",
    short: "Attention where queries, keys, and values all come from the same sequence.",
    long: "Self-attention lets every position in a sequence attend to every other position in that same sequence, which is what lets transformers model long-range dependencies without the vanishing-gradient problems of recurrent networks. Its naive compute and memory cost is O(n^2) in sequence length, which is the fundamental reason long-context models need engineering tricks (sparse attention, sliding windows, KV cache reuse) rather than just 'bigger matrices'.",
    related: ["attention", "multi-head-attention", "transformer"],
    moduleId: "fundamentals",
  },
  {
    id: "multi-head-attention",
    term: "Multi-Head Attention (MHA)",
    short: "Running several attention computations in parallel on different learned projections, then combining the results.",
    long: "Instead of one attention computation, MHA splits queries/keys/values into multiple smaller 'heads' that each learn to attend to different kinds of relationships (e.g. syntactic vs. coreference patterns), then concatenates and projects the results. Standard MHA keeps one full set of keys/values per head, which is the most memory-hungry variant for KV caching at inference time — this is exactly the cost that GQA and MQA were introduced to reduce.",
    related: ["attention", "grouped-query-attention", "multi-query-attention", "kv-cache"],
    moduleId: "fundamentals",
  },
  {
    id: "grouped-query-attention",
    term: "Grouped-Query Attention (GQA)",
    short: "An attention variant where multiple query heads share a smaller set of key/value heads to shrink the KV cache.",
    long: "GQA sits between full multi-head attention (one KV head per query head, highest quality, highest memory) and multi-query attention (one KV head total, lowest memory, more quality risk). By grouping query heads to share KV heads, modern inference-optimized models cut KV-cache memory substantially with a much smaller quality hit than MQA, which is why it is now common in production-oriented model architectures. The exact group size is an architecture detail you should check per model rather than assume.",
    related: ["multi-head-attention", "multi-query-attention", "kv-cache"],
    moduleId: "fundamentals",
  },
  {
    id: "multi-query-attention",
    term: "Multi-Query Attention (MQA)",
    short: "An attention variant where all query heads share a single key/value head, minimizing KV-cache size.",
    long: "MQA maximizes inference efficiency — one shared KV projection means the KV cache is a fraction of the size of full MHA, which matters enormously for long-context, high-batch serving. The trade-off is representational: sharing one KV head across all queries can measurably reduce quality versus MHA/GQA, so it is typically chosen by model builders optimizing hard for throughput/cost rather than a free lunch.",
    related: ["multi-head-attention", "grouped-query-attention", "kv-cache"],
    moduleId: "fundamentals",
  },
  {
    id: "transformer",
    term: "Transformer",
    short: "The neural network architecture built from stacked self-attention and feed-forward blocks that underlies virtually all modern LLMs.",
    long: "A transformer alternates self-attention layers (which mix information across token positions) with position-wise feed-forward layers (which transform each token's representation independently), wrapped in residual connections and normalization. Its key property versus RNNs/CNNs is that all positions can be processed in parallel during training (no sequential recurrence), which is what made training on today's massive datasets computationally feasible at all.",
    related: ["attention", "self-attention", "positional-encoding", "causal-masking"],
    moduleId: "fundamentals",
  },
  {
    id: "positional-encoding",
    term: "Positional Encoding",
    short: "A signal injected into token representations so the model knows token order, since attention itself is order-agnostic.",
    long: "Raw self-attention has no notion of sequence order — it treats input as a set, not a sequence — so models add positional information explicitly, either as fixed sinusoidal vectors added to embeddings (original transformer) or as relative schemes like RoPE applied inside attention. The choice of positional scheme directly affects how well a model generalizes to sequence lengths longer than it was trained on, which is a major factor in a model's practical, reliable context length versus its advertised maximum.",
    related: ["rotary-embedding", "transformer", "context-window"],
    moduleId: "fundamentals",
  },
  {
    id: "rotary-embedding",
    term: "Rotary Position Embedding (RoPE)",
    short: "A positional encoding scheme that rotates query/key vectors by an angle proportional to token position, encoding relative position directly in attention scores.",
    long: "RoPE encodes position as a rotation in a complex/2D subspace of each attention head, so the dot product between a rotated query and key naturally depends on their relative distance rather than absolute position. This relative-position property is a big part of why RoPE-based models can be extended to longer contexts via interpolation/extrapolation tricks (e.g. position scaling) more gracefully than models with fixed absolute positional embeddings — though quality at extended lengths still degrades and should be verified empirically, not assumed from the architecture alone.",
    related: ["positional-encoding", "context-window", "transformer"],
    moduleId: "fundamentals",
  },
  {
    id: "causal-masking",
    term: "Causal Masking",
    short: "Blocking attention to future tokens so an autoregressive model can only condition on what came before.",
    long: "Causal (or 'look-ahead') masking sets attention scores to negative infinity for any position after the current one, which is what forces a decoder-only LLM to generate strictly left-to-right and is why it can be trained efficiently on all positions of a sequence in parallel (teacher forcing) while still behaving autoregressively at inference. It is the structural reason prompt caching works at all: tokens before a given position never depend on tokens after it, so a cached prefix's computation is provably reusable as long as the prefix text is unchanged.",
    related: ["attention", "transformer", "autoregressive-decoding", "kv-cache"],
    moduleId: "fundamentals",
  },
  {
    id: "parameter-count",
    term: "Parameter Count",
    short: "The number of learned weights in a model, often used as a (noisy) proxy for capability and cost.",
    long: "Parameter count correlates loosely with capability and strongly with inference cost/memory, but it is not a reliable ranking signal on its own — training data quality, architecture choices (e.g. mixture-of-experts sparsity), and post-training (RLHF/DPO/distillation) all shift the capability-per-parameter ratio significantly. Treat any specific parameter count for a current hosted model as volatile and check provider docs; many providers no longer disclose it at all.",
    related: ["distillation", "quantization", "pretraining"],
    moduleId: "fundamentals",
  },
  {
    id: "autoregressive-decoding",
    term: "Autoregressive Decoding",
    short: "Generating output one token at a time, each conditioned on all previously generated tokens.",
    long: "Autoregressive decoding is why LLM generation is inherently sequential at inference time (unlike the parallel training step): token N+1 cannot be computed until token N's representation exists, which caps raw per-request throughput and is the reason streaming and KV caching matter so much for perceived latency. Techniques like speculative decoding (drafting several tokens with a cheap model and verifying with the full model) exist specifically to work around this sequential bottleneck.",
    related: ["kv-cache", "causal-masking", "time-to-first-token", "tokens-per-second"],
    moduleId: "fundamentals",
  },
  {
    id: "logit",
    term: "Logit",
    short: "The raw, unnormalized score a model assigns to each possible next token before softmax turns them into probabilities.",
    long: "Logits are what sampling parameters actually operate on: temperature rescales logits before softmax, top-k/top-p truncate the resulting probability distribution, and logit bias/logprobs features expose or adjust these raw scores directly. Understanding that temperature=0 does not literally mean 'no logits' but rather 'always pick the argmax logit' clarifies why greedy decoding can still change between provider versions if the underlying logits shift even slightly (model updates, kernel/precision differences).",
    related: ["temperature", "logprobs", "greedy-decoding", "top-k"],
    moduleId: "fundamentals",
  },
];
