import type { GlossaryTerm } from "../types";

export const trainingAdaptationTerms: GlossaryTerm[] = [
  {
    id: "pretraining",
    term: "Pretraining",
    short: "The initial, massive-scale self-supervised training phase where a model learns general language patterns from huge amounts of text.",
    long: "Pretraining (typically next-token prediction over a web-scale corpus) is what gives a model its broad general knowledge and language competence, and it is by far the most compute- and data-intensive phase of building a model — the phase most associated with the large published training costs and timelines. Everything downstream (SFT, RLHF/DPO, fine-tuning) adapts a pretrained model's behavior but cannot meaningfully add knowledge the pretraining corpus never contained at anywhere near the same scale, which is a key reason RAG exists as an alternative to retraining for fresh or private knowledge.",
    related: ["supervised-fine-tuning", "rlhf", "catastrophic-forgetting"],
    moduleId: "advanced",
  },
  {
    id: "supervised-fine-tuning",
    term: "Supervised Fine-Tuning (SFT)",
    short: "Further training a pretrained model on a curated dataset of (prompt, ideal response) pairs to teach a specific behavior or format.",
    long: "SFT is typically the step that turns a raw pretrained 'text completer' into an instruction-following assistant, by training on examples that look like the target behavior (following instructions, adopting a helpful tone, producing a specific format). It requires real labeled data quality — a small amount of high-quality, carefully curated examples often outperforms a much larger set of noisy ones — and it can still leave the model imperfectly aligned with nuanced human preferences, which is what RLHF/DPO are typically layered on top of to address.",
    related: ["pretraining", "rlhf", "dpo", "lora"],
    moduleId: "advanced",
  },
  {
    id: "rlhf",
    term: "RLHF (Reinforcement Learning from Human Feedback)",
    short: "Training a model to better match human preferences by optimizing it against a reward signal derived from human comparisons of its outputs.",
    long: "Classic RLHF trains a separate reward model on human-labeled preference comparisons (which of two responses is better), then uses reinforcement learning (commonly PPO) to adjust the base model's policy to produce outputs the reward model scores highly. It is effective at aligning a model's style and judgment with human preference beyond what SFT alone achieves, but it is complex, computationally expensive, and sensitive to reward-model quality — a flawed reward model can be 'gamed' (reward hacking) by the policy in ways that look good to the reward model but are not actually what humans wanted.",
    related: ["ppo", "dpo", "supervised-fine-tuning"],
    moduleId: "advanced",
  },
  {
    id: "ppo",
    term: "PPO (Proximal Policy Optimization)",
    short: "A reinforcement learning algorithm commonly used in RLHF to update a model's policy while limiting how far each update can shift it.",
    long: "PPO constrains each training update to stay within a bounded 'trust region' of the current policy, which prevents the kind of destructively large policy updates that can destabilize training entirely — a practical necessity when the reward signal (from a learned reward model) is itself imperfect and noisy. It is notably more complex to implement and tune correctly than simpler alternatives, which is part of why DPO has gained popularity as a lighter-weight alternative for preference alignment.",
    related: ["rlhf", "dpo"],
    moduleId: "advanced",
  },
  {
    id: "dpo",
    term: "DPO (Direct Preference Optimization)",
    short: "A preference-alignment method that directly optimizes a model on preference pairs without training a separate reward model or using reinforcement learning.",
    long: "DPO reformulates the RLHF objective into a simpler supervised-learning-style loss directly over (chosen, rejected) response pairs, eliminating the separate reward-model training stage and the instability/complexity of RL optimization (PPO) altogether. This makes it considerably simpler and cheaper to run than full RLHF while often achieving comparable alignment quality, which is why many modern open and commercial fine-tuning pipelines have shifted toward DPO (or related direct-preference methods) over classic RLHF.",
    related: ["rlhf", "ppo", "supervised-fine-tuning"],
    moduleId: "advanced",
  },
  {
    id: "lora",
    term: "LoRA (Low-Rank Adaptation)",
    short: "A parameter-efficient fine-tuning method that trains small low-rank 'adapter' matrices instead of updating the full model's weights.",
    long: "LoRA freezes the original pretrained weights and injects small trainable low-rank matrices into specific layers, dramatically reducing the number of trainable parameters (and therefore memory/compute) needed to adapt a model to a new task or domain compared to full fine-tuning. Because the base weights never change, multiple LoRA adapters can be trained independently and swapped in/out at inference time against the same base model, which is a major operational advantage for serving many fine-tuned variants cheaply.",
    related: ["qlora", "supervised-fine-tuning", "catastrophic-forgetting"],
    moduleId: "advanced",
  },
  {
    id: "qlora",
    term: "QLoRA (Quantized LoRA)",
    short: "LoRA fine-tuning performed on top of a quantized (lower-precision) base model to further cut memory requirements.",
    long: "QLoRA combines LoRA's parameter efficiency with quantization's memory efficiency, loading the frozen base model in a compressed low-precision format (e.g. 4-bit) while still training full-precision LoRA adapters on top — this is what made fine-tuning large models feasible on a single consumer or single-datacenter GPU rather than a large multi-GPU cluster. The quantization of the frozen base introduces some precision loss, so quality should be validated against the full-precision baseline for your specific task rather than assumed equivalent.",
    related: ["lora", "quantization"],
    moduleId: "advanced",
  },
  {
    id: "distillation",
    term: "Knowledge Distillation",
    short: "Training a smaller 'student' model to mimic the outputs (or internal behavior) of a larger 'teacher' model.",
    long: "Distillation lets you deploy a much cheaper, faster model that captures a useful fraction of a larger model's capability on a specific task distribution, by training the student on the teacher's outputs (or soft probability distributions) rather than on raw human-labeled data alone. The student's ceiling is bounded by the teacher's quality and by how well the distillation data covers the deployment task — a student distilled on narrow data can look great on similar inputs and fail badly on inputs outside that distribution, so it needs its own targeted evaluation, not just a comparison to the teacher's benchmark scores.",
    related: ["pretraining", "quantization"],
    moduleId: "advanced",
  },
  {
    id: "quantization",
    term: "Quantization",
    short: "Reducing the numeric precision used to store and compute a model's weights (e.g. 16-bit to 8-bit or 4-bit) to shrink memory and speed up inference.",
    long: "Quantization trades some numerical precision for substantial gains in memory footprint and often inference speed, which is what makes running large models on consumer hardware or serving them more cheaply at scale practical at all. Quality loss from quantization is generally graceful but not zero and not uniform across tasks — precision-sensitive tasks (exact arithmetic, code with subtle logic) tend to degrade more than fluent free-text generation, so any specific precision/quality trade-off claim should be treated as illustrative and verified empirically rather than taken as a universal benchmark number.",
    related: ["gguf", "awq", "gptq", "qlora"],
    moduleId: "advanced",
  },
  {
    id: "gguf",
    term: "GGUF",
    short: "A file format (successor to GGML) for storing quantized models, widely used by local-inference runtimes like llama.cpp and Ollama.",
    long: "GGUF bundles model weights, quantization metadata, and tokenizer information into a single portable file, which is why it became the de facto standard for running quantized open-weight models locally across different quantization levels (various bit-widths and schemes) without needing separate conversion tooling per runtime. The specific quantization scheme encoded in a GGUF file (e.g. different 4-bit variants) trades file size and speed against quality differently, and those trade-offs are runtime/version-specific details worth checking current documentation for rather than assuming from the format name alone.",
    related: ["quantization", "awq", "gptq"],
    moduleId: "advanced",
  },
  {
    id: "awq",
    term: "AWQ (Activation-Aware Weight Quantization)",
    short: "A quantization method that preserves accuracy by identifying and protecting the weights most sensitive to activation-driven error, before quantizing the rest aggressively.",
    long: "AWQ's key insight is that not all weights contribute equally to output error under quantization — by analyzing activation statistics, it identifies a small subset of 'salient' weights and scales them to minimize quantization error there, while quantizing the bulk of weights more aggressively. This generally preserves more quality at low bit-widths than naive uniform quantization, at the cost of a calibration step (requiring representative activation data) before the quantized model can be produced.",
    related: ["quantization", "gptq", "gguf"],
    moduleId: "advanced",
  },
  {
    id: "gptq",
    term: "GPTQ",
    short: "A post-training quantization method that quantizes weights layer-by-layer, minimizing the reconstruction error introduced at each step.",
    long: "GPTQ processes a model one layer at a time, solving a per-layer optimization problem to choose quantized weight values that minimize the error propagated to that layer's output, which generally yields strong accuracy at aggressive bit-widths (e.g. 4-bit or lower) without requiring retraining. Like other post-training quantization methods, its real-world quality impact is architecture- and task-dependent, so any specific accuracy-retention number belongs in 'check current benchmarks for the specific model' territory rather than being treated as a fixed universal figure.",
    related: ["quantization", "awq", "gguf"],
    moduleId: "advanced",
  },
  {
    id: "catastrophic-forgetting",
    term: "Catastrophic Forgetting",
    short: "A model losing previously-learned capabilities after being fine-tuned on new data, because the new training signal overwrites old learned patterns.",
    long: "Catastrophic forgetting is a core risk of any further training on a pretrained model — fine-tuning narrowly on a new task/domain can measurably degrade general capabilities the model had before, especially with small datasets, high learning rates, or too many training epochs on narrow data. Parameter-efficient methods like LoRA partially mitigate this by leaving the original weights frozen and untouched, but even adapter-based fine-tuning can still narrow a model's effective behavior within the task distribution it was fine-tuned on, so broad-capability regression testing (not just the new task's own metric) is warranted after any fine-tuning pass.",
    related: ["supervised-fine-tuning", "lora", "pretraining"],
    moduleId: "advanced",
  },
  {
    id: "synthetic-data",
    term: "Synthetic Data",
    short: "Training or evaluation data generated by a model rather than collected from real human-produced examples.",
    long: "Synthetic data is attractive because it is far cheaper and faster to produce at scale than human-labeled data, and it is widely used both for fine-tuning (generating varied training examples from a small set of seed examples) and for eval dataset expansion. Its risk is distributional narrowness and self-reinforcing bias — data generated by a model tends to reflect that model's own stylistic quirks, blind spots, and errors, so training heavily on synthetic data without any real-data grounding can amplify rather than correct a model's existing weaknesses; human-reviewed seed examples and periodic validation against real data remain important.",
    related: ["supervised-fine-tuning", "golden-dataset"],
    moduleId: "advanced",
  },
];
